### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by KQAR** [pujiaxin33/JXSegmentedView#1]
您好，您封装的这个工具挺好用的。我觉得有个地方改一下会更好，点击cell跳转页面的时候，如果相隔多个cell，页面滚动跳转的效果不太好，不如直接跳转。现在的app中应该都是这样跳的，点击cell没有滚动动画。滚动应该只用于相邻页面之间。

**Comment by pujiaxin33** [comment]
isContentScrollViewClickTransitionAnimationEnabled如果设置为false，点击切换的时候就不会有动画

**Comment by KQAR** [comment]
很抱歉，没仔细看就来提问题...
