### ISSUE TITLE
iOS 11以上safeAreaInsets问题和collectView刷新问题

### ISSUE THREAD

**Issue by ZXCheng** [pujiaxin33/JXSegmentedView#102]
1：在iOS11以上设备，JXSegmentedListContainerType = .scrollView时，未适配刘海屏的安全域
2：当JXSegmentedListContainerType = .collectionView时，containerView 里面包含纯UITextView显示纯文本，开始显示或者通过segmented选中某一页时并不能加载文本

**Comment by pujiaxin33** [comment]
> 1：在iOS11以上设备，JXSegmentedListContainerType = .scrollView时，未适配刘海屏的安全域
请参考【刷新数据+JXSegmentedListContainerView】示例，并没有出现【未适配刘海屏】问题。

**Comment by pujiaxin33** [comment]
> 2：当JXSegmentedListContainerType = .collectionView时，containerView 里面包含纯UITextView显示纯文本，开始显示或者通过segmented选中某一页时并不能加载文本

请提供可以复现问题的demo
