### ISSUE TITLE
点击切换segment，页面还没有切换完成就触发listDidAppear

### ISSUE THREAD

**Issue by changelee82** [pujiaxin33/JXSegmentedView#105]
我已将设置了 listContainerView.initListPercent = 0.99，
手动拖拽页面时，页面切换完成后才触发listDidAppear，
点击segment时，点击的瞬间就执行listDidAppear，怎样才能等页面切换完成后再触发listDidAppear。
非常感谢

**Comment by pujiaxin33** [comment]
点击的时候，没有使用initListPercent属性，仅在手动拖拽时才生效。

**Comment by changelee82** [comment]
我想在页面完全出现后，执行一些操作，原计划是写在listDidAppear中，但是点击时，页面还没有完全出现，就触发了listDidAppear，不知道应该怎么实现。
