### ISSUE TITLE
二级界面使用JXSegmentedView出现宽度还未计算完就出现数据源过少的效果

### ISSUE THREAD

**Issue by 1284115201** [pujiaxin33/JXSegmentedView#107]
这种现象不是100%出现，而是数据源过少的时候偶尔出现

**Comment by pujiaxin33** [comment]
麻烦提供一个可以复现问题的demo

**Comment by 1284115201** [comment]
> 麻烦提供一个可以复现问题的demo

最近赶项目，没时间整理，我推测应该是第一次计算宽度时还没计算完就已经显示了，计算完后下次进入该二级界面就正常了，当然有时候第一次就正常的，后来我没用自动计算，自己给了固定宽度解决

**Comment by pujiaxin33** [comment]
贴一下出问题时的关键代码呢？
