### ISSUE TITLE
如何禁用顶部点击

### ISSUE THREAD

**Issue by JessYan0913** [pujiaxin33/JXSegmentedView#109]
有这样一个需求，顶部的tab不能点击，类似于UIPageControl的作用。但是奈何UIPageControl的样式过于单一，JXSegmentedView又没有禁用tab点击的属性。有没有什么更好的方法嘛？

**Comment by pujiaxin33** [comment]
你是想说顶部状态栏？

**Comment by JessYan0913** [comment]
> 你是想说顶部状态栏？

是的

**Comment by JessYan0913** [comment]
想实现的是顶部状态栏不可点击，但是跟随contentScrollView而变化

**Comment by JessYan0913** [comment]
请问JXSegmentedView可以实现这样的需求嘛？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "暴走的鑫鑫"<notifications@github.com&gt;; 
发送时间: 2020年7月20日(星期一) 下午4:18
收件人: "pujiaxin33/JXSegmentedView"<JXSegmentedView@noreply.github.com&gt;; 
抄送: "严恒"<1141326491@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pujiaxin33/JXSegmentedView] 如何禁用顶部点击 (#109)





 
你是想说顶部状态栏？

**Comment by pujiaxin33** [comment]
第一，你可以看一下UIScrollView.scrollsToTop属性的解释。
第二，你可以在listDidAppear代理方法，把列表的scrollsToTop设置为true。
