### ISSUE TITLE
效果实现

### ISSUE THREAD

**Issue by simpleLiYu** [pujiaxin33/JXSegmentedView#111]
![image](https://user-images.githubusercontent.com/20043672/88778702-6ada4380-d1bb-11ea-8587-95831b6348ef.png)
大佬这种效果能实现吗

**Comment by pujiaxin33** [comment]
你可以参考[JXCategoryView](https://github.com/pujiaxin33/JXCategoryView)相关示例，就是自定义cell视图内容。

**Comment by simpleLiYu** [comment]
好的，我模仿一下。感谢
