### ISSUE TITLE
selectItemAt(index: Int) 该方法能否增加参数支持动画选项：selectItemAt(index: Int, animated: Bool = true)

### ISSUE THREAD

**Issue by bosong** [pujiaxin33/JXSegmentedView#113]

**Comment by bosong** [comment]
有时候 viewDidAppear 进入页面需要选中一个index不是0 的item，目前调用方法selectItemAt 默认有滚动动画，能否增加参数支持动画选项？方法类似 这样写 func selectItemAt(index: Int, animated: Bool = true)，是否需要选中动画由用户使用场景决定。

**Comment by pujiaxin33** [comment]
可以设置defatulSelectedIndex

**Comment by bosong** [comment]
@pujiaxin33 , defatulSelectedIndex 应该只能在初始化的过程中使用吧？例如当前controller A有一个JXSegmentedView，之后push一个controller  B，回到controller A的时候需要把JXSegmentedView 选中第三个item，且不需要动画，这种情况用defatulSelectedIndex 是实现不了的。

**Comment by qingweiSun** [comment]
同求，页数太多的时候，不要动画

**Comment by nieyu** [comment]
设置下面属性可以控制不滚动

> segmentedView.isContentScrollViewClickTransitionAnimationEnabled = false

**Comment by Plotac** [comment]
> 设置下面属性可以控制不滚动
> 
> > segmentedView.isContentScrollViewClickTransitionAnimationEnabled = false

这个属性不行... 同求控制动画接口
