### ISSUE TITLE
从非第一个 tabbar  的list pushController 侧滑卡死

### ISSUE THREAD

**Issue by chihaodong** [pujiaxin33/JXSegmentedView#126]
这个有人遇到过没有， 3上 navbar，第一个 list 点击Push ，侧滑没有问题， 第二个，第三个 list 点击 pushController时 侧滑卡死，页面卡住，怎么解决

**Comment by pujiaxin33** [comment]
能通过demo复现吗？我需要排除你是否使用了某些其他三方库导致的问题。

**Comment by 1284115201** [comment]
我也有这样的情况，多个的时候会卡顿
