### ISSUE TITLE
请问列表左右滑动的时候怎么刷新 segmentView ？

### ISSUE THREAD

**Issue by mokyz** [pujiaxin33/JXSegmentedView#13]
我只想刷新标题文字，我在左右滑动列表的时候执行 JXSegmentedTitleDataSource.reloadData(selectedIndex:)，但是此时我应该传哪个 index 呢？有没有可以直接更新标题文字的方法呢？

**Comment by pujiaxin33** [comment]
你的需求是从A滑动到B的时候，就更新B的文字吗？
或者你举个例子，具体表达下你的目标需求。

**Comment by mokyz** [comment]
我的意思是只更新所有标题文字，而不是重置他们的视图。如果在左右滑动的过程中调用 reloaddata，会重置所有的标题视图，就会闪一下，滑动的进度也被重置了。

**Comment by pujiaxin33** [comment]
那刷新标题的逻辑是怎么样的呢？
A滑动到B，只刷新A、B，还是刷新所有标题？

**Comment by mokyz** [comment]
刷新所有标题。我现在是滚动完全停止，才去刷新标题，也算实现需求了，所以只是提个想法，

**Comment by pujiaxin33** [comment]
目前可行的方案:
第一个就是你提的：滚动完全停止，才去刷新标题；
第二个：`JXSegmentedTitleDataSource`先重新赋值`titles`，并调用`reloadData(selectedIndex: 传入当前选中index)`，然后再循环index调用`reloadItem(at index: Int)`方法。
