### ISSUE TITLE
关于“PagingViewController”这个模版，我container中是两个并排联动的tableview

### ISSUE THREAD

**Issue by ysjava** [pujiaxin33/JXSegmentedView#130]
像美团外卖中店铺里面的点餐页，两个联动的tableview， 而JXPagingViewListViewDelegate中的func listScrollView() -> UIScrollView {} 只能返回一个，所以不知道该怎么去做

**Comment by pujiaxin33** [comment]
"两个联动的tableview" 这只是属于一种特殊的listView，需要你自己定义。
