### ISSUE TITLE
screen is empty

### ISSUE THREAD

**Issue by waleedmakarem** [pujiaxin33/JXSegmentedView#132]
Dear Sir, 
Thanks for the library, looks great. 
I am new to swift, I try to make simple use of the library with the following code, but screen is empty, though I add the segmentedviewcontrol to may main view.

class ViewController: UIViewController {
var segmentedDataSource: JXSegmentedTitleDataSource!
   var segmentedView: JXSegmentedView! 
override func viewDidLoad() {
    super.viewDidLoad()
    // Do any additional setup after loading the view.
    view.backgroundColor = .white
    segmentedView = JXSegmentedView()
    segmentedDataSource = JXSegmentedTitleDataSource()
           segmentedDataSource.titles = ["cat" , "dog" , "lion"]
           segmentedDataSource.isTitleColorGradientEnabled = true
           segmentedView.dataSource = segmentedDataSource
   self.view.addSubview(self.segmentedView)
}

**Comment by pujiaxin33** [comment]
You should retain the instance of JXSegmentedTitleDataSource() in your view controller.
