### ISSUE TITLE
请问能否做到不让点击某一个title？

### ISSUE THREAD

**Issue by chenfengfeng** [pujiaxin33/JXSegmentedView#136]
首先非常感谢作者开源的这个库

我们现在有一个需求，在一些情况下，需要不可点击某个title。

比如现在有三个title

在已经禁止滑动的情况下，就只能通过点击title来切换

想在这个基础上，禁止点击中间的title

这样应该怎么做比较好呢？能不能不改动源码？
我看了title用的是UICollectionView来做的，理论是可以禁用cell的点击，但不清楚有没有提供API

**Comment by chenfengfeng** [comment]
啊，这么快就被自己解决了，对API不熟悉的错

在代理里面就可以实现这个功能了

func segmentedView(_ segmentedView: JXSegmentedView, canClickItemAt index: Int) -> Bool

另外，如果想让不能点击的title的字体颜色变其他颜色，能这样吗？

**Comment by chenfengfeng** [comment]
自己修改了datasource文件搞定了

**Comment by ChenLianghui** [comment]
怎么改的啊兄弟，找了半天不知道怎么改，这么明显的bug，作者应该修复一下啊 @pujiaxin33

**Comment by mujinweixiao** [comment]
怎么改的啊，求指教

**Comment by Liyongcong** [comment]
怎么改的啊，求指教
