### ISSUE TITLE
使用该库，原项目采用 setNavigationBarHidden 的方式隐藏导航栏，在返回时候会闪现！！！demo 如下

### ISSUE THREAD

**Issue by zeqinjie** [pujiaxin33/JXSegmentedView#147]
[DEMO](https://github.com/pujiaxin33/JXSegmentedView/files/5854058/JXSegmentedView-TEST.zip) 是作者给的基础上加了我自己项目的代码
点击 红色的 button 在 push 我自己的页面（ZQViewController 设置隐藏系统导航栏）。用侧滑手势，返回会闪现系统导航栏！请问作者是什么原因造成？谢谢
`[self.navigationController setNavigationBarHidden:YES animated:animated];`

**Comment by xiaoliang1410** [comment]
你解决了吗，我也是这个问题，导航栏隐藏了， 点击的时候不会出现系统导航栏，滑动的时候会出现

**Comment by xiaoliang1410** [comment]
因为他滑动时候相当于是跳转了页面，所以要在消失的时候也将系统导航栏隐藏，加上这两句
//解决滑动时系统导航栏显示的问题
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.isNavigationBarHidden = true
        mainTable.reloadData()
    }
    //解决滑动时系统导航栏显示的问题
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        navigationController?.isNavigationBarHidden = true
    }

**Comment by zeqinjie** [comment]
> 你解决了吗，我也是这个问题，导航栏隐藏了， 点击的时候不会出现系统导航栏，滑动的时候会出现

pod 'KMNavigationBarTransition' 依赖这个库解决了
