### ISSUE TITLE
能否增加一个当数据较少的时候 中心居中的效果

### ISSUE THREAD

**Issue by superk589** [pujiaxin33/JXSegmentedView#148]
#41 类似这个 Issue 但是还不完全一样 
效果类似 UIStackView.distribution = .equalCentering

应用的场景是：当有3个tab，但是文字数量互不相等，比如分别是 3、4、5，希望中间的tab和导航栏标题能够中心对齐
目前仅仅设置 isItemSpacingAverageEnabled = true 的效果如下，无法满足这个需求
<img width="330" alt="image" src="https://user-images.githubusercontent.com/19667784/105458997-76b74600-5cc4-11eb-98b6-8beda8048d26.png">

**Comment by League2EB** [comment]
支持该想法，如果可以有这个方法会是很不错的！
