### ISSUE TITLE
roundCorners 设定左上，右上 弧度，弧度部分背景白色无法更改

### ISSUE THREAD

**Issue by o1xhack** [pujiaxin33/JXSegmentedView#150]
通过以下代码，成功实现了弧度，但是因为我设定的所有界面底色都是黑色，设定完后，弧度空余地方全部为白色。

        segmentedView.roundCorners([.topLeft, .topRight], radius: 22)

最外的 view 和 segmentedView，pagingview 设定 background color 都是黑色。 实现后如下图：

![image](https://user-images.githubusercontent.com/10677990/109469138-994d3380-7aa8-11eb-9df9-1ab4f03f9b20.png)

**Comment by znblyj** [comment]
可以通过以下代码设置弧度空余地方的背景色
```
pagingView.mainTableView.backgroundColor = .red
```
