### ISSUE TITLE
关于 JXCategoryTitleVerticalZoomView

### ISSUE THREAD

**Issue by MrBugDou** [pujiaxin33/JXSegmentedView#159]
您好，之前使用您的JXCategoryView，现在换到swift版本以后，想要实现这个效果：
![image](https://user-images.githubusercontent.com/12947653/114514449-d3266380-9c2a-11eb-8644-08814b146301.png)
发现swift版本没有JXCategoryTitleVerticalZoomView类，于是打算仿照JXCategoryTitleVerticalZoomView自己实现一个，
继承 JXSegmentedTitleDataSource 实现，但是发现swift版本缺少这个两个属性
![image](https://user-images.githubusercontent.com/12947653/114515155-93ac4700-9c2b-11eb-8990-eea160c651d6.png)
导致无法实现锚点位于底部的垂直缩放效果，所以想请教一下我应该怎么去修改

**Comment by pujiaxin33** [comment]
Swift和OC并不完全一致
