### ISSUE TITLE
JXPagingView+JXSegmentedView结合使用，push之后pop回来，listDidAppear调用index不对

### ISSUE THREAD

**Issue by speeddream** [pujiaxin33/JXSegmentedView#16]
JXPagingView1.1.4版本，JXSegmentedView也替换成最新的版本
在此demo的Personal个人主页中可以复现

把索引传递给子view，push之后pop回来
左右滚动子view的情况，pop回来listDidAppear打印的是上一页的index
点击segment title的情况，pop回来listDidAppear打印正常

暂时解决方案
在个人主页viewWillAppear中pagingView.reloadData()，但是会重新创建子view
有没有更好的方法

**Comment by pujiaxin33** [comment]
自测没有问题，你能提供一个有问题的demo工程吗？

**Comment by speeddream** [comment]
好的，demo参照JXSegmentedView的Personal，麻烦看一下
[PagingView.zip](https://github.com/pujiaxin33/JXSegmentedView/files/3124864/PagingView.zip)

**Comment by pujiaxin33** [comment]
这是swift版本的问题，1.1.5版本修复

**Comment by pujiaxin33** [comment]
这是JXPagingView swift版本的问题，在JXPagingView的1.1.5版本修复
