### ISSUE TITLE
富文本 titleLabel.textAlignment = .center 不生效

### ISSUE THREAD

**Issue by FunnyerFeng** [pujiaxin33/JXSegmentedView#160]
JXSegmentedTitleAttributeDataSource+ JXSegmentedTitleAttributeCell 配合实现富文本的UI时，传入一个带换行符的富文本字符串
titleLabel.textAlignment = .center 不生效
目前解决的办法是重写下面的方法重新设置一下textAlignment
open override func reloadData(itemModel: JXSegmentedBaseItemModel, selectedType: JXSegmentedViewItemSelectedType) {
        super.reloadData(itemModel: itemModel, selectedType: selectedType )
        titleLabel.textAlignment = .center
    }

**Comment by pujiaxin33** [comment]
已修复
