### ISSUE TITLE
请问下指示器 JXSegmentedIndicatorBackgroundView 怎么设定未选中状态下的背景颜色？？

### ISSUE THREAD

**Issue by GFGWin** [pujiaxin33/JXSegmentedView#164]

**Comment by realPX** [comment]
indicatorColor

**Comment by GFGWin** [comment]
没有。。

**Comment by smalls0098** [comment]
防止大家踩坑，我给大家搞了一个出来了。
``` swift
import UIKit
import JXSegmentedView

open class ReserveJXSegmentedTitleDataSource: JXSegmentedTitleDataSource {
    
    open override func segmentedView(_ segmentedView: JXSegmentedView, cellForItemAt index: Int) -> JXSegmentedBaseCell {
        let cell = super.segmentedView(segmentedView, cellForItemAt: index)
        cell.layer.cornerRadius = 5
        return cell
    }
    
    open override func registerCellClass(in segmentedView: JXSegmentedView) {
        segmentedView.collectionView.register(ReserveJXSegmentedTitleCell.self, forCellWithReuseIdentifier: "cell")
    }
    
}

open class ReserveJXSegmentedTitleCell: JXSegmentedTitleCell {
    
    open override func reloadData(itemModel: JXSegmentedBaseItemModel, selectedType: JXSegmentedViewItemSelectedType) {
        if itemModel.isSelected {
            backgroundColor = .nw_main
        } else {
            backgroundColor = .nw_FAFAFA
        }
        super.reloadData(itemModel: itemModel, selectedType: selectedType)
    }
    
}
```
就是没动画效果，然后需要把JXSegmentedView的indicators设置为[]，大家按照自己项目需求搞搞

**Comment by zy364601065** [comment]
`class JXSegmentedNormalBgTitleCell: JXSegmentedTitleCell {
    
    let bgView = UIView()

    open override func commonInit() {
        super.commonInit()

        bgView.clipsToBounds = true
        contentView.insertSubview(bgView, at: 0)
    }

    open override func layoutSubviews() {
        super.layoutSubviews()
        
        guard let myItemModel = itemModel as? JXSegmentedNormalBgTitleItemModel else {
            return
        }
        let labelSize = titleLabel.sizeThatFits(self.contentView.bounds.size)
        var height = labelSize.height
        if myItemModel.bgHeight != JXSegmentedViewAutomaticDimension {
            height = myItemModel.bgHeight
        }
        bgView.frame = CGRect(x: titleLabel.frame.minX - myItemModel.bgWidthIncrement / 2.0, y: titleLabel.frame.minY - (height - labelSize.height) / 2.0, width: labelSize.width + myItemModel.bgWidthIncrement, height: height)
        bgView.layer.cornerRadius = height / 2.0
    }

    open override func reloadData(itemModel: JXSegmentedBaseItemModel, selectedType: JXSegmentedViewItemSelectedType) {
        super.reloadData(itemModel: itemModel, selectedType: selectedType )
        
        guard let myItemModel = itemModel as? JXSegmentedNormalBgTitleItemModel else {
            return
        }

        if myItemModel.isSelected {
            bgView.backgroundColor = myItemModel.bgSelectedColor
        } else {
            bgView.backgroundColor = myItemModel.bgNormalColor
        }

        setNeedsLayout()
    }
}
`

**Comment by zy364601065** [comment]
```
class JXSegmentedNormalBgTitleCell: JXSegmentedTitleCell {
    
    let bgView = UIView()

    open override func commonInit() {
        super.commonInit()

        bgView.clipsToBounds = true
        contentView.insertSubview(bgView, at: 0)
    }

    open override func layoutSubviews() {
        super.layoutSubviews()
        
        guard let myItemModel = itemModel as? JXSegmentedNormalBgTitleItemModel else {
            return
        }
        let labelSize = titleLabel.sizeThatFits(self.contentView.bounds.size)
        var height = labelSize.height
        if myItemModel.bgHeight != JXSegmentedViewAutomaticDimension {
            height = myItemModel.bgHeight
        }
        bgView.frame = CGRect(x: titleLabel.frame.minX - myItemModel.bgWidthIncrement / 2.0, y: titleLabel.frame.minY - (height - labelSize.height) / 2.0, width: labelSize.width + myItemModel.bgWidthIncrement, height: height)
        bgView.layer.cornerRadius = height / 2.0
    }

    open override func reloadData(itemModel: JXSegmentedBaseItemModel, selectedType: JXSegmentedViewItemSelectedType) {
        super.reloadData(itemModel: itemModel, selectedType: selectedType )
        
        guard let myItemModel = itemModel as? JXSegmentedNormalBgTitleItemModel else {
            return
        }

        if myItemModel.isSelected {
            bgView.backgroundColor = myItemModel.bgSelectedColor
        } else {
            bgView.backgroundColor = myItemModel.bgNormalColor
        }

        setNeedsLayout()
    }
}
``` 自定义一个cell 这样就完美了

**Comment by zy364601065** [comment]
class JXSegmentedNormalBgTitleCell: JXSegmentedTitleCell {
    
    let bgView = UIView()

    open override func commonInit() {
        super.commonInit()

        bgView.clipsToBounds = true
        contentView.insertSubview(bgView, at: 0)
    }

    open override func layoutSubviews() {
        super.layoutSubviews()
        
        guard let myItemModel = itemModel as? JXSegmentedNormalBgTitleItemModel else {
            return
        }
        let labelSize = titleLabel.sizeThatFits(self.contentView.bounds.size)
        var height = labelSize.height
        if myItemModel.bgHeight != JXSegmentedViewAutomaticDimension {
            height = myItemModel.bgHeight
        }
        bgView.frame = CGRect(x: titleLabel.frame.minX - myItemModel.bgWidthIncrement / 2.0, y: titleLabel.frame.minY - (height - labelSize.height) / 2.0, width: labelSize.width + myItemModel.bgWidthIncrement, height: height)
        bgView.layer.cornerRadius = height / 2.0
    }

    open override func reloadData(itemModel: JXSegmentedBaseItemModel, selectedType: JXSegmentedViewItemSelectedType) {
        super.reloadData(itemModel: itemModel, selectedType: selectedType )
        
        guard let myItemModel = itemModel as? JXSegmentedNormalBgTitleItemModel else {
            return
        }

        if myItemModel.isSelected {
            bgView.backgroundColor = myItemModel.bgSelectedColor
        } else {
            bgView.backgroundColor = myItemModel.bgNormalColor
        }

        setNeedsLayout()
    }
}
 自己自定义一个cell 这样就完美了

**Comment by Liyongcong** [comment]
> JXSegmentedNormalBgTitleItemModel

JXSegmentedNormalBgTitleItemModel这个itemModel怎么配置的
