### ISSUE TITLE
Cannot find protocol definition for 'JXSegmentedListContainerViewDataSource'

### ISSUE THREAD

**Issue by wubangshun** [pujiaxin33/JXSegmentedView#165]
oc混编swift, 在 "项目名-swift.h" 文件中提示Cannot find protocol definition for 'JXSegmentedListContainerViewDataSource'， 我单独把JXSegmentedListContainerViewDataSource所在文件注释后，源码拷贝到工程中新建的文件中就编译通过了，知道这个啥原因造成的吗，实在找不到解决办法了。
![image](https://user-images.githubusercontent.com/11895372/118348606-14899600-b57e-11eb-8bce-c5dbc405eb6c.png)

**Comment by iqcc** [comment]
一样的问题

**Comment by pujiaxin33** [comment]
OC建议使用JXCategoryView

**Comment by DavidLius** [comment]
最新版还是一样的问题。并不是oc调用它，而是在混编项目中，swift文件调用它。但因为它在库里标注@objc，导致编译时，报错。
