### ISSUE TITLE
如果 title下增加背景色如何实现 ，类似指示器的样式

### ISSUE THREAD

**Issue by RuYiChenIT** [pujiaxin33/JXSegmentedView#169]

**Comment by kacok** [comment]
楼上有解决方案吗？

**Comment by yxphby** [comment]
> 楼上有解决方案吗？

我按照OC版写了一份已经解决了，需要代码的话可以联系我

**Comment by yxphby** [comment]
> 楼上有解决方案吗？

我按照OC版写了一份已经解决了，需要代码的话可以联系我

**Comment by greezi** [comment]
> > 楼上有解决方案吗？
> 
> 我按照OC版写了一份已经解决了，需要代码的话可以联系我

可以分享下代码吗，蟹蟹大佬~

**Comment by Liyongcong** [comment]
> > 楼上有解决方案吗？
> 
> 我按照OC版写了一份已经解决了，需要代码的话可以联系我

需要类似oc那样的，能发下代码吗大佬

**Comment by Liyongcong** [comment]
> > > 楼上有解决方案吗？
> > 
> > 
> > 我按照OC版写了一份已经解决了，需要代码的话可以联系我
> 
> 可以分享下代码吗，蟹蟹大佬~

能发下代码吗大佬
