### ISSUE TITLE
元素列表中的cell需要传控制器的时候会闪退

### ISSUE THREAD

**Issue by DuQuanzhong** [pujiaxin33/JXSegmentedView#178]
Terminating app due to uncaught exception 'UIViewControllerHierarchyInconsistency', reason: 'child view controller:<AVPlayerViewController: 0x1049b3c00> should have parent view controller:<JXSegmentedView.JXSegmentedListContainerViewController: 0x1050e9e90> but actual parent is:<NwdnBeta.NwdnStoryHomeViewController: 0x10466b040>

JXSegmentedListContainerViewController 这个控制器我看是私有的 怎么能获取到 谢谢

**Comment by pujiaxin33** [comment]
对于列表是VC的情况，你外部使用的地方就不要addChild：列表VC了。
