### ISSUE TITLE
No 'listContainerView' candidates produce the expected contextual result type 'JXSegmentedViewListContainer?'

### ISSUE THREAD

**Issue by fenglongteng** [pujiaxin33/JXSegmentedView#182]
extension JXPagingListContainerView: JXSegmentedViewListContainer {}

**Comment by kkkelicheng** [comment]
我也有这个报错。我当时还想着这demo怎么就没这个问题。。。
难道要进行类型转换。
应该是楼主的方法要多写一个extension。

**Comment by yuyedaidao** [comment]
加上又报重复 😭
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/6354958/163090983-7bfcf56c-28d4-4ef8-babe-8e93bd6df83c.png">
