### ISSUE TITLE
IOS15系统mini系列手机，分页滚动会有问题

### ISSUE THREAD

**Issue by lxm1799** [pujiaxin33/JXSegmentedView#183]
IOS15系统mini系列手机，分页滚动会有问题，目前仅发现在IOS15系统的mini系列手机上有bug

**Comment by jackiehu** [comment]
试了试所有的collectview横向滚动都有问题，系统的APP也是一样，貌似mini的模拟器都这样

**Comment by pujiaxin33** [comment]
通过demo测试，这应该是iOS 15 iphone mini 系统手机自己的问题，写一个最简单的demo，进行视图动画，也会出现动画残影的问题。
