### ISSUE TITLE
 IOS15，点击tab切换界面会卡住

### ISSUE THREAD

**Issue by FukeYang** [pujiaxin33/JXSegmentedView#184]

**Comment by BeingCode** [comment]
+1

**Comment by pujiaxin33** [comment]
如何复现呢？

**Comment by jackiehu** [comment]
> 

在15.0.1  和 15.0.2  系统上频繁点击Segmentview就出现了

**Comment by ruins-hacker** [comment]
hello @pujiaxin33 这个有预期什么时候修复嘛...

**Comment by DNC-7** [comment]
> w 574行修改如下
> if contentScrollView != nil && (selectedType == .click || selectedType == .code) {
> // contentScrollView!.setContentOffset(CGPoint(x: contentScrollView!.bounds.size.width_CGFloat(index), y: 0), animated: isContentScrollViewClickTransitionAnimationEnabled) if isContentScrollViewClickTransitionAnimationEnabled { UIView.animate(withDuration: 0.25) { self.contentScrollView?.contentOffset = CGPoint(x: self.contentScrollView!.bounds.size.width_CGFloat(index), y: 0)
> }
> }else{
> contentScrollView?.contentOffset = CGPoint(x: contentScrollView!.bounds.size.width*CGFloat(index), y: 0)
> }
> }

请问这个是什么原理呢
