### ISSUE TITLE
不显示内容，datasource 直接就是 nil，应该是被释放了

### ISSUE THREAD

**Issue by pikacode** [pujiaxin33/JXSegmentedView#188]
datasource 应该不用 weak 吧？现在我在代码中必须用一个变量持有 datasource，否则就被释放了，内容全是空的
还有建议 space 不要加到前面，前面单独给个属性类似 leadingSpace 这样，包括后面也是
还有 datasource 都是直接赋值，delegate 建议不要用代理了，直接用 block 赋值这样可以统一

**Comment by pujiaxin33** [comment]
datasource最开始是按照代理的方式设计的，后面就修改为了注入的形式，确实不该用weak。目前datasource需要自己持有。
