### ISSUE TITLE
看一下特殊效果个人主页  分页上部分会留有20左右的空白

### ISSUE THREAD

**Issue by 861271841** [pujiaxin33/JXSegmentedView#189]
以前没有这个问题。可能出现在iOS 15。  你的demo也一样。

**Comment by dreamguagua** [comment]
我也遇到这个问题

**Comment by dreamguagua** [comment]
@861271841  
 if #available(iOS 15.0, *) {
            tableView.sectionHeaderTopPadding = 0
        } else {

        }
可以解决，因为15多了sectionHeaderTopPadding属性，还默认不是0 ，不知道苹果怎么想的

**Comment by 861271841** [comment]
@dreamguagua  谢谢
