### ISSUE TITLE
Line宽度、滑动手势相关问题

### ISSUE THREAD

**Issue by changelee82** [pujiaxin33/JXSegmentedView#19]
1、如何设置Line固定宽度，并且宽度填满Cell，比如3个cell，每个line的长度是屏幕的三分之一。
2、如何设置在某个页面上不允许左右滑动手势，比如，滑动到第二个页面后，让手势无效，只能点击cell切换页面。

**Comment by pujiaxin33** [comment]
> 如何设置Line固定宽度，并且宽度填满Cell，比如3个cell，每个line的长度是屏幕的三分之一。
- indicatorWidth = JXSegmentedViewAutomaticDimension
- JXSegmentedBaseDataSource.itemContentWidth = ScreenWidth/3
- JXSegmentedBaseDataSource.itemSpacing = 0

> 如何设置在某个页面上不允许左右滑动手势，比如，滑动到第二个页面后，让手势无效，只能点击cell切换页面。
当滑动到第二个页面后，设置JXSegmentedListContainerView.scrollView.isScrollEnabled = false，其他页面再更新回来

**Comment by changelee82** [comment]
谢谢您，已经看到效果了。
