### ISSUE TITLE
貌似没有设置默认选中的方法

### ISSUE THREAD

**Issue by walkstep** [pujiaxin33/JXSegmentedView#2]
默认选中都是第一个，可否提供方法，选中其他index

**Comment by pujiaxin33** [comment]
可以通过配置defaultSelectedIndex属性实现

**Comment by mokyz** [comment]
设置了defaultSelectedIndex属性但是样式好像并没有符合预期
<img width="387" alt="image" src="https://user-images.githubusercontent.com/8747328/56203320-904f4680-6077-11e9-8c4f-83fce98a5680.png">
