### ISSUE TITLE
设置为navigationItem.titleView会导致被导航栏控制器持有不销毁

### ISSUE THREAD

**Issue by YongTaiSin** [pujiaxin33/JXSegmentedView#202]
如果在上一个页面的导航栏是隐藏的，当前页面的导航栏是显示的，当前页面设置titleView为segmentedView会导致pop回去这个控件仍然没销毁，只有在viewWillDisappear里设置为nil才能解决。 但是这样会导致手势返回一半titleView空白的现象。
![image](https://user-images.githubusercontent.com/10525179/156956387-04a5bf44-f1fb-495e-8645-35e01ef7f967.png)

**Comment by pujiaxin33** [comment]
在NaviSegmentedControlViewController example中并没有复现你所说的内存泄露问题。

**Comment by iAmMccc** [comment]
我也遇到了这个问题。 因为导航栏是唯一的（系统的UINavigationController），将segmentView放到        navigationItem.titleView = mainSegmentView，页面和导航栏的生命周期不同步，mainSegmentView被导航栏强支持有，因此mainSegmentView持有的listContainerView，listContainerView持有的vc也不会被释放。
