### ISSUE TITLE
SegmentedTitleCell 有警告

### ISSUE THREAD

**Issue by DNC-7** [pujiaxin33/JXSegmentedView#209]
Xcode 提示优化 Optimization Opportunities: The layer is using a simple layer with background color set as a mask. Instead, use a container layer of the same frame and cornerRadius as the mask, but with masksToBounds set to YES.

**Comment by DeveloperMan7** [comment]
![image](https://user-images.githubusercontent.com/19930889/171562235-a0668895-8553-4156-b395-9cf69a2b6557.png)
注释掉 不使用就好了

**Comment by DeveloperMan7** [comment]
或者Podfile里添加：
post_install do |installer|
  find_and_replace("Pods/JXSegmentedView/Sources/Title/JXSegmentedTitleCell.swift",
    "            maskTitleLabel.isHidden = true", "            maskTitleLabel.isHidden = true\n            maskTitleLabel.layer.mask = nil")
end
#注入代码到指定文件
def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      FileUtils.chmod("+w", name) #add
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end

**Comment by DNC-7** [comment]
> ![image](https://user-images.githubusercontent.com/19930889/171562235-a0668895-8553-4156-b395-9cf69a2b6557.png) 注释掉 不使用就好了

好的，感谢回复

**Comment by DeveloperMan7** [comment]
> > ![image](https://user-images.githubusercontent.com/19930889/171562235-a0668895-8553-4156-b395-9cf69a2b6557.png) 注释掉 不使用就好了
> 
> 好的，感谢回复

不破坏原有代码结构的话 就在第141行的maskTitleLabel.isHidden = true 后面加 maskTitleLabel.layer.mask = nil，如果是使用pod的话就用我以下的文本放入Podfile，前面那个有点小问题，一个空格都不能少哦，字符串查找替换的：

post_install do |installer|
  find_and_replace("Pods/JXSegmentedView/Sources/Title/JXSegmentedTitleCell.swift",
    "            maskTitleLabel.isHidden = true\n            titleLabel.layer.mask = nil","            maskTitleLabel.isHidden = true\n            maskTitleLabel.layer.mask = nil\n            titleLabel.layer.mask = nil")
end
#注入代码到指定文件
def find_and_replace(dir, findstr, replacestr)
Dir[dir].each do |name|
FileUtils.chmod("+w", name) #add
text = File.read(name)
replace = text.gsub(findstr,replacestr)
if text != replace
puts "Fix: " + name
File.open(name, "w") { |file| file.puts replace }
STDOUT.flush
end
end
Dir[dir + '*/'].each(&method(:find_and_replace))
end
