### ISSUE TITLE
iOS 10的系统下 contentScrollView 上的视图  上下滑动

### ISSUE THREAD

**Issue by leisong1125** [pujiaxin33/JXSegmentedView#21]
在iOS10 的系统下 contentScrollView 上 可左右滑动的视图 ，也可以上下滑动（就像ScrollView 允许上下左右滑动一样）,其实segmentedView只应该 允许左右滑动，其他系统下未发现这种状况

**Comment by pujiaxin33** [comment]
最近升级了xcode11，找不到ios10的模拟器了，晚些时候去复现一下

**Comment by leisong1125** [comment]
本来 我想尝试着更新到最新版本0.0.16来看是不是版本问题，更新之后程序崩溃
<img width="1377" alt="屏幕快照 2019-06-10 下午5 19 50" src="https://user-images.githubusercontent.com/14797836/59185919-3913b100-8ba4-11e9-93d8-2e9e726abdd5.png">
然后下载Git上最新的源码 运行程序也崩溃
<img width="426" alt="1622408-e9577344437a916b" src="https://user-images.githubusercontent.com/14797836/59185981-56e11600-8ba4-11e9-89bb-bcae39813123.png">
源码崩溃 解决之后 进入程序点击任意一个样式也崩溃
<img width="1392" alt="屏幕快照 2019-06-10 下午5 23 39" src="https://user-images.githubusercontent.com/14797836/59186065-8a23a500-8ba4-11e9-85e6-aa0853b0f769.png">

**Comment by pujiaxin33** [comment]
你的手机系统是多少？
xcode版本是多少?

**Comment by leisong1125** [comment]
手机系统12.0，Xcode10.1

**Comment by pujiaxin33** [comment]
已经更新example工程，你再试试呢

**Comment by leisong1125** [comment]
git的源码没问题了，但是我项目里更新了0.0.16还是崩溃

**Comment by leisong1125** [comment]
我当前用的是0.0.4

**Comment by pujiaxin33** [comment]
我自己更新到了0.0.16没有问题，你clean一下项目再运行试试呢

**Comment by leisong1125** [comment]
是的，clean之后没问题了，然后我升级了0.0.16之后 视图上下滑动在IOS 10 下，暂未复现，后面再测试一下，谢谢！！！

**Comment by leisong1125** [comment]
视图在iOS 10的下面 还是可以上下滑动(在左右滑动的时候 也可以上下滑动)
<img width="883" alt="屏幕快照 2019-06-24 18 56 00" src="https://user-images.githubusercontent.com/14797836/60013723-bdd8f180-96b1-11e9-96dc-8822054f7e6b.png">
<img width="840" alt="屏幕快照 2019-06-24 18 55 42" src="https://user-images.githubusercontent.com/14797836/60013769-de08b080-96b1-11e9-9717-68e9bae1c809.png"> 
代码的约束在其他系统上未出现

**Comment by pujiaxin33** [comment]
你用frame布局呢？指不定就是系统的bug

**Comment by pujiaxin33** [comment]
咱们惹不起，总躲得起卅
