### ISSUE TITLE
使用Xcode的Debug View Hierarchy查看视图层级时有Optimization Opportunities警告

### ISSUE THREAD

**Issue by viihua** [pujiaxin33/JXSegmentedView#210]
![image](https://user-images.githubusercontent.com/19930889/171561815-eac15600-657b-4be9-b1bc-ba589010b0e3.png)
![image](https://user-images.githubusercontent.com/19930889/171561894-99032fa0-6dea-440e-9238-bb8ea79f0f00.png)
初步判断是JXSegmentedTitleCell中的maskTitleLabel导致的，没有使用到遮罩Title.
![image](https://user-images.githubusercontent.com/19930889/171562127-d223112d-414a-4965-95e8-07db615fc491.png)

**Comment by DeveloperMan7** [comment]
@pujiaxin33 大牛看看有没有什么问题。
自己研究了下，认为不破坏原有代码结构的话 就在第141行的maskTitleLabel.isHidden = true 后面加 maskTitleLabel.layer.mask = nil，如果是使用pod的话就用我以下的文本放入Podfile，前面那个有点小问题，一个空格都不能少哦，字符串查找替换的：


post_install do |installer|
find_and_replace("Pods/JXSegmentedView/Sources/Title/JXSegmentedTitleCell.swift",
" maskTitleLabel.isHidden = true\n titleLabel.layer.mask = nil"," maskTitleLabel.isHidden = true\n maskTitleLabel.layer.mask = nil\n titleLabel.layer.mask = nil")
end
#注入代码到指定文件
def find_and_replace(dir, findstr, replacestr)
Dir[dir].each do |name|
FileUtils.chmod("+w", name) #add
text = File.read(name)
replace = text.gsub(findstr,replacestr)
if text != replace
puts "Fix: " + name
File.open(name, "w") { |file| file.puts replace }
STDOUT.flush
end
end
Dir[dir + '*/'].each(&method(:find_and_replace))
end

**Comment by pujiaxin33** [comment]
已修复
