### ISSUE TITLE
滑动到一半又取消滑动处理 会导致子vc的viewDidDisappear异常调用

### ISSUE THREAD

**Issue by zhoujun951236** [pujiaxin33/JXSegmentedView#215]
手指移到滚动视图超过一半，放手会导致此问题
![image](https://user-images.githubusercontent.com/6309671/196074619-3572f900-7c6c-4604-ab2a-747e5c440723.png)
猜测是这块没有根据偏移量做真实切换意图的判断。没有超过一半这块是没有问题，超过一半偏移放手确实切换过去了，这就和这块代码实现冲突了

**Comment by Monkey-Sun** [comment]
这个后续的解决方案是啥？
