### ISSUE TITLE
选中和未选中内容不同时，不会自动调整宽度

### ISSUE THREAD

**Issue by iosborer** [pujiaxin33/JXSegmentedView#217]
要求选中和未选中状态内容不同，item宽度也就肯能不同，这个怎么整？

**Comment by EdwinXiang** [comment]
老铁改了吗，我也遇到这个问题

**Comment by wanxiangxiang** [comment]
子视图超出父视图了
![图片](https://github.com/pujiaxin33/JXSegmentedView/assets/24890090/c83ca825-8840-43cd-9c09-363618a1b8db)
