### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by wenhaoChan** [pujiaxin33/JXSegmentedView#218]
Hi,
I found out there was a crash in bugly

here's my code: （system : iOS 15.7 (19H12)）

the cell returned from -collectionView:cellForItemAtIndexPath: does not have a reuseIdentifier - cells must be retrieved by calling -dequeueReusableCellWithReuseIdentifier:forIndexPath:

0
CoreFoundation
___exceptionPreprocess + 216
5
UIKitCore
-[UICollectionView layoutSubviews] + 316
6
layoutSubviews (JXSegmentedCollectionView.swift:29)
7
layoutSubviews (:0)
8
UIKitCore
-[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2556
18
UIKitCore
-[UINavigationController setNavigationBarHidden:animated:] + 156
19
_$sSo22UINavigationControllerC8FlatBaseE36setupNavigationBarAppearanceIfNeeded013appearingViewB0ySo06UIViewB0C_tFyAG_SbtcfU0_TA (:0)
20
_$sSo16UIViewControllerCSbIeggy_AB10ObjectiveC8ObjCBoolVIeyByy_TR (:0)
21
_$sSo16UIViewControllerCSbIeggy_ABSbytIegnnr_TRTA (:0)
22
_$sSo16UIViewControllerCSbytIegnnr_ABSbIeggy_TRTA (:0)
23
_$sSo16UIViewControllerCSbIeggy_AB10ObjectiveC8ObjCBoolVIeyByy_TR (:0)

I hope you can help me on this.

Thanks.

**Comment by pujiaxin33** [comment]
Thanks for your information. I have identified the issues and fixed it.
