### ISSUE TITLE
这种样式该怎么做

### ISSUE THREAD

**Issue by wqforever** [pujiaxin33/JXSegmentedView#222]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/15868474/210530140-53836261-ef6e-4c64-a7f9-13847161e806.png">

**Comment by Jyhwenchai** [comment]
正好遇到这个情况，需要自定义JXSegmentedBaseDataSource 

![image](https://user-images.githubusercontent.com/10082674/219297343-e55f494e-b78e-4dea-9518-5c553344e47b.png)

**Comment by pujiaxin33** [comment]
是的，请参考上面的自定义代码。
