### ISSUE TITLE
稳定的crash: 刷新数据+JXSegmentedListContainerView 

### ISSUE THREAD

**Issue by liusr** [pujiaxin33/JXSegmentedView#225]
您好，刷新数据+JXSegmentedListContainerView ，在这个例子中，有如下crash场景：
LoadDataViewController中配置数据源添加segmentedDataSource.isItemWidthZoomEnabled = true
然后在getRandomTitles方法中每次让数据源减少，刷新后不点击标题，直接左右滑动底部的列表会crash。
原因出在animator?.progressClosure中维持了旧的index导致下面的代码越界。

**Comment by pujiaxin33** [comment]
感谢反馈，已修复。
