### ISSUE TITLE
UICollectionView和UITableView中存在了左右滑动样式和JXCategoryListContainerView左右滑动切换冲突

### ISSUE THREAD

**Issue by taojeff** [pujiaxin33/JXSegmentedView#227]
我的JXCategoryListContainerView中的contentlistView中是用UICollectionView和UITableView实现的，可是这时候出现了不固定的页面出现和JXCategoryListContainerView左右滑动手势冲突

**Comment by WineKai** [comment]
你好，这个问题解决没？我也碰到这种情况

**Comment by taojeff** [comment]
> 你好，这个问题解决没？我也碰到这种情况

解决了，我发现是我的cell样式没有增加到self.contentView上导致的。你也可以查看一下

**Comment by WineKai** [comment]
> > 你好，这个问题解决没？我也碰到这种情况
> 
> 解决了，我发现是我的cell样式没有增加到self.contentView上导致的。你也可以查看一下

你好，想问下cell的什么样式需要增加到cell.contentView上？
