### ISSUE TITLE
在设置完titleSelectedColor之后，能否再次设置titleSelectedColor

### ISSUE THREAD

**Issue by djliu2** [pujiaxin33/JXSegmentedView#230]
目前发现第二次设置titleSelectedColor不再生效

**Comment by uclort** [comment]
segmentView.reloadData()
segmentView.reloadDataWithoutListContainer()

**Comment by pujiaxin33** [comment]
> segmentView.reloadData() segmentView.reloadDataWithoutListContainer()

更新配置之后，需要调用reloadData()
