### ISSUE TITLE
关于当JXSegmentedCollectionView的ContentSize小于父视图宽度时整体居中的问题

### ISSUE THREAD

**Issue by wxw962530118** [pujiaxin33/JXSegmentedView#239]
举例说明如下：
1.JXSegmentedView与当前父视图都是屏幕宽度，但是在数据源很少的时候（JXSegmentedCollectionView的ContentSize小于父视图宽度），设置contentEdgeInsetLeft和contentEdgeInsetRight并不能达到整体居中，相同配置在两台设备上显示效果完全不同
iPad效果
<img width="514" alt="Snipaste_2023-12-03_22-26-24" src="https://github.com/pujiaxin33/JXSegmentedView/assets/19562349/d26fb998-5f48-4b19-b22f-40d9a72abd31">
iPhone效果
<img width="341" alt="Snipaste_2023-12-03_22-27-06" src="https://github.com/pujiaxin33/JXSegmentedView/assets/19562349/46d7f5b5-bed6-4ac5-895c-5eef2c274fbd">

**Comment by pujiaxin33** [comment]
可以参考《导航栏使用》示例，让JXSegmentedView居中显示在视图中，但是宽度只是内容宽度。
