### ISSUE TITLE
能否创建 Subspecs ? ，我只需要基本功能，想要缩小项目体积

### ISSUE THREAD

**Issue by lizhi0123** [pujiaxin33/JXSegmentedView#241]
是否可以创建子 pod，subspecs, 可以更 自由的选择需要的文件。 
比如：我只需要基本功能，想要缩小项目体积
类似
- Subspecs:
     - JXSegmentedView/Core 
     - JXSegmentedView/Title 
     - JXSegmentedView/SubTitle 
     - JXSegmentedView/SubTitleImage 
     - JXSegmentedView/TitleImage 
     - JXSegmentedView/TitleOrImage 
     - JXSegmentedView/TitleGradient 
     - JXSegmentedView/AttributeTitle 
     - JXSegmentedView/Dot 
     - JXSegmentedView/DotZoom 
     - JXSegmentedView/Number 
     - JXSegmentedView/Badge 
     - JXSegmentedView/Indicator 
     - JXSegmentedView/Indicator/Background 
     - JXSegmentedView/Indicator/Line 
     - JXSegmentedView/Indicator/AlignmentLine 
     - JXSegmentedView/Indicator/Gradient 
     - JXSegmentedView/Indicator/GradientLine 
     - JXSegmentedView/Indicator/DotLine 
     - JXSegmentedView/Indicator/DoubleLine 
     - JXSegmentedView/Indicator/RainbowLine 
     - JXSegmentedView/Indicator/Triangle 
     - JXSegmentedView/Indicator/Image

**Comment by pujiaxin33** [comment]
可以自己fork一份，然后删除，然后项目引入你自己的git地址。
