### ISSUE TITLE
怎么刷新指定的ContainerView。页面完成网络请求了，调用reloadData，又要重新请求。

### ISSUE THREAD

**Issue by RchTimeK** [pujiaxin33/JXSegmentedView#242]
怎么刷新指定的ContainerView。页面完成网络请求了，调用reloadData，又要重新请求。

**Comment by AcceleratorYY** [comment]
在你容器子页面你定义个变量 比如 let isLoadOnce = false , 你加载完请求 isLoadOnce = true

**Comment by pujiaxin33** [comment]
你可以自己把列表缓存起来，可以参考demo中的【列表缓存】示例。
