### ISSUE TITLE
segmentedView.reloadDataWithoutListContainer 导致没有滚动动画！

### ISSUE THREAD

**Issue by PZXforXcode** [pujiaxin33/JXSegmentedView#243]
//点击选中或者滚动选中都会调用该方法。适用于只关心选中事件，而不关心具体是点击还是滚动选中的情况。
    func segmentedView(_ segmentedView: JXSegmentedView, didSelectedItemAt index: Int) {
        
        if index == 0 {

            //这里有逻辑需要根据PCRecommendViewController的上滑情况来显示样式
            segmentedDataSource?.titleSelectedColor = .white
            indicator.indicatorColor = .white
            segmentedDataSource?.titleNormalColor = UIColor.init(hexString: "#FFFFFF",alpha: 0.5)!
        }else{

            //固定样式
            indicator.indicatorColor = .black
            segmentedDataSource?.titleSelectedColor = #colorLiteral(red: 0, green: 0, blue: 0, alpha: 1)
            segmentedDataSource?.titleNormalColor = #colorLiteral(red: 0.4, green: 0.4, blue: 0.4, alpha: 1)

        }

        segmentedView.reloadDataWithoutListContainer()
    }
这样就没有滚动动画了

**Comment by pujiaxin33** [comment]
1.3.3版本已添加JXSegmentedTitleDynamicConfiguration feature，参考Title Configuration示例即可。
