### ISSUE TITLE
是否可以支持这种效果？

### ISSUE THREAD

**Issue by tipshot** [pujiaxin33/JXSegmentedView#245]
<img width="298" alt="image" src="https://github.com/pujiaxin33/JXSegmentedView/assets/18547353/67e6af60-ca3d-4d21-ab0f-7ac45e4a17b8">
<img width="292" alt="image" src="https://github.com/pujiaxin33/JXSegmentedView/assets/18547353/4c3cd1b9-96f9-41c1-94b0-dbb30861cb45">

**Comment by pujiaxin33** [comment]
无法支持
