### ISSUE TITLE
使用JXSegmentedTitleImageDataSource时，设置titleImageType为leftImage时，maskTitleLabel的位置不对，会与图片重叠

### ISSUE THREAD

**Issue by Hjt830** [pujiaxin33/JXSegmentedView#246]
使用JXSegmentedTitleImageDataSource时，设置titleImageType为leftImage时，maskTitleLabel的位置不对，会与图片重叠。
![image](https://github.com/pujiaxin33/JXSegmentedView/assets/13915006/409eea08-ea6e-48e9-9e3a-be346c09d710)
这里应该加一行代码，把maskTitleLabel的center设置为titleLabel的center
"""
maskTitleLabel.center = titleLabel.center
"""

**Comment by pujiaxin33** [comment]
已按照你的建议进行了修复🤝
