### ISSUE TITLE
有一个需求，没登录的时候，禁止显示关注页

### ISSUE THREAD

**Issue by linyongbin** [pujiaxin33/JXSegmentedView#248]
现在的情况是，可以禁止顶部点击，但是底部的滚动没法禁止，只是没加载试图而已
要如何做到滚动到关注页之前，禁止滚动？
![image](https://github.com/pujiaxin33/JXSegmentedView/assets/14193605/dc4344c8-9b0c-487d-8733-218f4d1e8075)

**Comment by pujiaxin33** [comment]
如果你只有两个tab的话，那么可以设置JXSegmentedListContainerView.scrollView.isScrollEnabled = false。
