### ISSUE TITLE
使用Xcode 16 beta build project會出現build error

### ISSUE THREAD

**Issue by manuellam1991** [pujiaxin33/JXSegmentedView#249]
錯誤如下
/Pods/JXSegmentedView/Sources/Indicator/JXSegmentedIndicatorGradientView.swift:121:68 'CAMediaTimingFunctionName' is only available in iOS 12.0 or newer

目前解決方法是在對應pod library
JXSegmentedView裡更改minimum deployments為iOS 12.0或以上

**Comment by moshiwu** [comment]
也可以
CAMediaTimingFunctionName.easeOut  ->  .easeOut

**Comment by pujiaxin33** [comment]
感谢反馈，预计会在1.3.4修复。
