### ISSUE TITLE
你好，listContainerView中添加tableview

### ISSUE THREAD

**Issue by Ezrealz** [pujiaxin33/JXSegmentedView#26]
左右滑动listContainerView和上下滑动tableview同时相应，导致体验不太好，有没有api可以优化一下呢？

**Comment by pujiaxin33** [comment]
不知道你的视图层级是怎么样的？

**Comment by Ezrealz** [comment]
您好 我是在listContainerView中嵌套了tableview ,导致我左右切换segment的时候 我的tableview列表也会响应滚动的事件

**Comment by pujiaxin33** [comment]
你发个截图或者GIF呢？

**Comment by Ezrealz** [comment]
![gif](https://user-images.githubusercontent.com/15242120/60559317-a5866800-9d7e-11e9-9560-7955eaaddcc7.gif)
您好，不知道我这个gif能不能跟您表述清楚我的问题。
我希望的是 我左右滑动listContainerView的时候我的tableview列表是不可以滚动的

**Comment by pujiaxin33** [comment]
建议你仔细参考demo写法，因为demo正常使用时没有这个问题的。
或者你在你电脑上面运行一下demo，看看demo是否有问题。

**Comment by Ezrealz** [comment]
我仔细看了一下您的demo，找到了解决办法 谢谢了

**Comment by YGEqual** [comment]
怎么解决的啊？按照demo写的 也还是这个问题
