### ISSUE TITLE
在ScrollView下嵌套使用导致无法上下滚动

### ISSUE THREAD

**Issue by zhumj** [pujiaxin33/JXSegmentedView#28]
1. 层级关系

ScrollView { 
    UIView { 
        UIView（固定高度）, 
        SegmentedView（固定高度）, 
        UIView { 
           JXSegmentedListContainerView {
               n个 UITableViewController
           }
        }
    }
} 

2. 最外层的ScrollView和最里层的UITableViewController都无法滚动，SegmentedView的Tab可以左右滚动

**Comment by pujiaxin33** [comment]
我觉得你截个图会更直观一下

**Comment by zhumj** [comment]
> 我觉得你截个图会更直观一下

最后还是用了你的 JXPagingView 方案解决嵌套滚动的问题
