### ISSUE TITLE
titleNumberOfLines	不起作用

### ISSUE THREAD

**Issue by Darren-chenchen** [pujiaxin33/JXSegmentedView#3]
self.segmentedDataSource.itemContentWidth = 50
 self.segmentedDataSource.titleNumberOfLines =0
 segmentedDataSource.reloadData(selectedIndex: 0)
<img width="443" alt="qq20190222-170025 2x" src="https://user-images.githubusercontent.com/16269032/53231226-62770280-36c3-11e9-929c-2b839090965a.png">

**Comment by pujiaxin33** [comment]
目前未对titleLabel的宽度做约束，正在研究方案确定

**Comment by Darren-chenchen** [comment]
我发延迟0.1s可以解决这个问题   
self.segmentedDataSource.itemContentWidth =  50
DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0.1) {
                self.segmentedView.reloadData()
            }

**Comment by pujiaxin33** [comment]
不明觉厉，如果能行就先将就用吧，后续方案确定再官方支持

**Comment by pujiaxin33** [comment]
其实不用调用
```Swift
DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0.1) {
self.segmentedView.reloadData()
}
```
参考最新仓库的【多行文字(固定宽度自动换行】示例
