### ISSUE TITLE
跨多个切换时，动画效果有点卡顿啊。

### ISSUE THREAD

**Issue by azureplus** [pujiaxin33/JXSegmentedView#31]
跨多个切换时，动画效果有点卡顿啊。

**Comment by azureplus** [comment]
跨多个切换时，底部也进行了多个切换，在哪可以直接设置值进行目标和当前的切换

**Comment by azureplus** [comment]
segmentedView.isContentScrollViewClickTransitionAnimationEnabled = false

这个临时解决

**Comment by pujiaxin33** [comment]
是的，就是它
