### ISSUE TITLE
请问一下不搭配滚动页面，JXSegmentedView可以单独使用么？

### ISSUE THREAD

**Issue by zhumj** [pujiaxin33/JXSegmentedView#32]
就像Android的TabLayout一样，有没有滚动页面Tab都可以显示

**Comment by pujiaxin33** [comment]
当然可以啦，就当做segmentedcontrol用就行

**Comment by pujiaxin33** [comment]
你就不要创建`JXSegmentedListContainerView`，不要`segmentedView.contentScrollView = listContainerView.scrollView`代码即可。

**Comment by zhumj** [comment]
哦哦，我不创建JXSegmentedListContainerView的话Tab显示不出来，可能是我哪里设置有错误，我再看看
