### ISSUE TITLE
您好，请问怎么可以只刷新标题文字？

### ISSUE THREAD

**Issue by mokyz** [pujiaxin33/JXSegmentedView#33]
我现在执行 segmentedView.reloadData() 会刷新整个 segmentedView，有时候会导致标题颜色变化，缩放会闪一下，想知道怎么可以只刷新 segmentedView 标题的文字，而不是重新刷新整个 segmentedView

**Comment by pujiaxin33** [comment]
目前有函数`func reloadItem(at index: Int)`刷新指定某一个item。
如果你刷新了标题文字，那对应的下方列表也要刷新吗？

**Comment by mokyz** [comment]
下方列表无所谓，最好不刷新，因为要刷新列表之后才能刷新标题，不过影响不大。主要是想只刷新标题的文字，标题的样式和指示器当前的状态都不刷新。因为可能在刷新标题的时候正在左右滑动。

**Comment by pujiaxin33** [comment]
关键是如果只刷新文字，比如“蜜蜂”刷新为“勤劳的小蜜蜂”，字符长度有很大的区别。如果是刷新文字，不刷新其他配置，就会显示超出范围。

**Comment by pujiaxin33** [comment]
你尝试自己依次调用`func reloadItem(at index: Int)`方法试试，能否满足需求
