### ISSUE TITLE
innerItemSpacing 这个控制左右item间距，可以暴露出来方法吗？需要自定义下

### ISSUE THREAD

**Issue by burning-git** [pujiaxin33/JXSegmentedView#37]
open func reloadData() {
        dataSource?.registerCellClass(in: self)
        if let itemSource = dataSource?.itemDataSource(in: self) {
            itemDataSource = itemSource
        }
        if selectedIndex < 0 || selectedIndex >= itemDataSource.count {
            defaultSelectedIndex = 0
            selectedIndex = 0
        }

        innerItemSpacing = dataSource?.itemSpacing ?? 0

**Comment by pujiaxin33** [comment]
`innerItemSpacing `这个是内部真实的间距属性，不能暴露哈。
请问你要实现什么效果呢？

**Comment by burning-git** [comment]
自定义 item  之间的间距。。。

itemSpacing 是最左边间距，innerItemSpacing 是两个item之间的间距。。
目前  innerItemSpacing 没法自定义。

**Comment by pujiaxin33** [comment]
itemSpacing是两个item之间的间距，contentEdgeLeft是最左边的边距，contentEdgeRight是最右边的边距

**Comment by burning-git** [comment]
哦哦，好的，我看见了！

**Comment by burning-git** [comment]
thanks
