### ISSUE TITLE
设置默认选中defaultSelectedIndex后 segmentedViewDataSource的第一个数据的颜色是选中的

### ISSUE THREAD

**Issue by haidumou** [pujiaxin33/JXSegmentedView#39]
假如segmentedView默认选中第3个，正常第1个数据应该不是选中的颜色，而是默认选中第3个数据颜色被选中，而现在segmentedViewDataSource的第一个数据的颜色是选中的，

**Comment by pujiaxin33** [comment]
在初始化或者调用reloadData方法之前，通过设置defaultSelectedIndex属性更新默认选中index。比如将defaultSelectedIndex设置为1，就会默认显示第二个列表。与此同时也要调用dataSource的reloadData(selectedIndex: 1)。保证JXSegmentedView与dataSource的默认选中index一致。

**Comment by haidumou** [comment]
找到了，谢谢！！！
