### ISSUE TITLE
能不能增加一个居中显示的效果啊

### ISSUE THREAD

**Issue by findM** [pujiaxin33/JXSegmentedView#41]
能不能增加一个居中显示的效果啊

数据较少的时候 居中显示

**Comment by findM** [comment]
`
if dataSource?.isCenter == true && totalContentWidth < bounds.size.width{
            contentEdgeInsetLeft = (bounds.size.width - totalContentWidth + getContentEdgeInsetRight() + getContentEdgeInsetLeft()) / 2
            contentEdgeInsetRight = contentEdgeInsetLeft
        }
`

搞定了

**Comment by pujiaxin33** [comment]
👍

**Comment by iOSyifeng** [comment]
> `if dataSource?.isCenter == true && totalContentWidth < bounds.size.width{ contentEdgeInsetLeft = (bounds.size.width - totalContentWidth + getContentEdgeInsetRight() + getContentEdgeInsetLeft()) / 2 contentEdgeInsetRight = contentEdgeInsetLeft }`
> 
> 搞定了
这是什么意思 没看懂 在dataSource里写?
