### ISSUE TITLE
设置了indicator宽度动态变化后，滑动切换到一半再松开，indicator的宽度不对

### ISSUE THREAD

**Issue by fingerplay** [pujiaxin33/JXSegmentedView#43]
如图，设置了indicator的宽度为内容-24，然后滑到一半回来时就不对了
![image](https://user-images.githubusercontent.com/988390/65414922-40935900-de27-11e9-9779-fb2e2b1797b8.png)

![image](https://user-images.githubusercontent.com/988390/65415136-b3043900-de27-11e9-9c19-e1c82f724144.png)

看了下代码，这个地方滑动时应该使用getIndicatorWidth 返回的宽度，而不是预先设定好的leftItemFrame和rightItemFrame的宽度

![image](https://user-images.githubusercontent.com/988390/65414447-518f9a80-de26-11e9-9c43-ac68593071b8.png)

**Comment by pujiaxin33** [comment]
已经采用你的PR进行了修复，非常感谢，稍后会打一个新包更新。
