### ISSUE TITLE
字体颜色与指示条位置不匹配

### ISSUE THREAD

**Issue by zhuamaodeyu** [pujiaxin33/JXSegmentedView#45]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
`Version`:  __0.0.19__
## What did you expect to happen?
1. CollectionView cell 添加 JXSegmentedView 
2. cell will enter screen 
3. 第一次显示正常，当滚动到第二个标签时， 如果cell滚出屏幕，再次滚入屏幕，此处显示不正常  
     * 指示器显示正常  
     * 高亮文字显示不正常，显示上一个为高亮  
4. 默认当前选中颜色与普通模式颜色相同，容易引起混淆

**Comment by zhuamaodeyu** [comment]
JXSegmentedTitleCell 文件的 73 行  
            if myItemModel.isSelected {
                titleLabel.font = myItemModel.titleSelectedFont
                maskTitleLabel.font = myItemModel.titleSelectedFont
            }else {
                titleLabel.font = myItemModel.titleNormalFont
                maskTitleLabel.font = myItemModel.titleNormalFont
            }
        }

**Comment by pujiaxin33** [comment]
0.0.21版本修复
