### ISSUE TITLE
选择自定义当前位置的时候，样式和指示器不跟着变化

### ISSUE THREAD

**Issue by lanfangqian** [pujiaxin33/JXSegmentedView#46]

**Comment by pujiaxin33** [comment]
能贴出相关代码么？
> 选择自定义当前位置的时候
这句话理解不到具体含义。

**Comment by qxc122** [comment]
比如  我在demo里加一句      tt.defaultSelectedIndex = 2;
- (JXCategoryBaseView *)preferredCategoryView {
    JXCategoryBaseView *tt = [[JXCategoryTitleView alloc] init];
    tt.defaultSelectedIndex = 2;
    return tt;
}
然后打开时候跳转到第二个了，但是页面没有出来，要滑动一下才会出来
@pujiaxin33

**Comment by pujiaxin33** [comment]
加上listContainerView. defaultSelectedIndex = 2
