### ISSUE TITLE
请问JXSegmentedListContainerView如何支持右滑返回 FDFullscreenPopGesture 这个库

### ISSUE THREAD

**Issue by buptjz** [pujiaxin33/JXSegmentedView#47]
大神你好，用了这个库觉得非常好用，在项目中已经集成，现在遇到一个问题是：
使用了JXSegmentedListContainerView，但这个类似乎不支持FDFullscreenPopGesture的右滑返回，想问下如何能够兼容？

而用JXPagingView的时候，可以用下面这个回调函数来支持
`
    func pagingListContainerCollectionView(_ collectionView: JXPagingListContainerCollectionView, gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        if collectionView.contentOffset.x <= 0 {
            guard let delegate = otherGestureRecognizer.delegate else {return false}
            guard let delegateClass = NSClassFromString("_FDFullscreenPopGestureRecognizerDelegate") else {return false}
            if delegate.isKind(of: delegateClass) {
                return true
            }
        }
        return false
    }
`

**Comment by pujiaxin33** [comment]
```Swift
/// 返回自定义UIScrollView实例
    /// 某些特殊情况需要自己处理UIScrollView内部逻辑。比如项目用了FDFullscreenPopGesture，需要处理手势相关代理。
    ///
    /// - Parameter listContainerView: JXSegmentedListContainerView
    /// - Returns: 自定义UIScrollView实例
    @objc optional func scrollView(in listContainerView: JXSegmentedListContainerView) -> UIScrollView
```

**Comment by pujiaxin33** [comment]
你可以借鉴OC版本的解决方法：[FDFullscreenPopGesture等全屏手势处理](https://github.com/pujiaxin33/JXCategoryView/blob/master/Document/%E5%85%A8%E5%B1%8F%E6%89%8B%E5%8A%BF%E5%A4%84%E7%90%86.md)
