### ISSUE TITLE
0.0.21版本颜色渐变效果失效

### ISSUE THREAD

**Issue by iamjjh** [pujiaxin33/JXSegmentedView#48]
JXSegmentedTitleDataSource的isTitleColorGradientEnabled属性为true的情况，并没有渐变效果，在0.0.20版本上正常。

**Comment by pujiaxin33** [comment]
1.0.0版本已经修复，请参考[1.0.0版本迁移指南](https://github.com/pujiaxin33/JXSegmentedView/blob/master/Document/1.0.0%E7%89%88%E6%9C%AC%E8%BF%81%E7%A7%BB%E6%8C%87%E5%8D%97.md)
