### ISSUE TITLE
能否增加一个更改每个title背景图片的api

### ISSUE THREAD

**Issue by LaurelYu** [pujiaxin33/JXSegmentedView#5]

**Comment by pujiaxin33** [comment]
你的意思是每个title下面都放一个背景图片？

**Comment by LaurelYu** [comment]
titleImageStr

> 你的意思是每个title下面都放一个背景图片？

目前有一个需求就是，每个titleLabel默认都是椭圆阴影。

**Comment by pujiaxin33** [comment]
建议使用自定义完成特定需求

**Comment by LaurelYu** [comment]
> 建议使用自定义完成特定需求

有自定义的api么？我没找到，麻烦给个提示，谢谢

**Comment by pujiaxin33** [comment]
参考文档的自定义和参考源码类
