### ISSUE TITLE
不想使用指示器，只想用JXSegmentedListContainerView该怎么做？

### ISSUE THREAD

**Issue by changelee82** [pujiaxin33/JXSegmentedView#50]
类似轮播图，没有指示器，但是想得到页面改变的事件。

**Comment by pujiaxin33** [comment]
轮播图，建议你使用这个库：https://github.com/WenchaoD/FSPagerView

**Comment by dawnnnnn** [comment]
> 轮播图，建议你使用这个库：https://github.com/WenchaoD/FSPagerView

我使用 `FSPagerView` 和 `JXSegmentedView` 联动，当我使用的` FSPagerViewCell`的宽度比屏幕宽度小的时候，我通过点击`JXSegmentedView`能切换到想去的分页，但是滑动`FSPagerView`，无法使`JXSegmentedView`去到我想去的标题。
有什么办法吗

**Comment by WineKai** [comment]
> 
确实，写到最后，发现无法点击滚动或者获取滚动的回调
