### ISSUE TITLE
segmentedView.reloadData() 会导致内存泄漏

### ISSUE THREAD

**Issue by buptjz** [pujiaxin33/JXSegmentedView#51]
你好，profiling过程中，发现segmentedView.reloadData()会导致内存泄漏
具体可见 LoadDataViewController 这个例子中，LoadDataListViewController不会被自动释放

**Comment by pujiaxin33** [comment]
自测并没有发现内存泄漏，你能看下你那边泄漏的地方吗？

**Comment by buptjz** [comment]
我用的是[LifetimeTracker](https://github.com/krzysztofzablocki/LifetimeTracker#lifetimetracker) 这个工具，重复点击刷新，LoadDataListViewController的count 会持续增加

**Comment by pujiaxin33** [comment]
你可以用instruments试试呢
