### ISSUE TITLE
segmentedView.selectItemAt(index: index)方法无效

### ISSUE THREAD

**Issue by zxmatline** [pujiaxin33/JXSegmentedView#53]
不管我怎么设置，这个方法总是无效，跳转不到指定的Tab:
//segmentedViewDataSource一定要通过属性强持有！！！！！！！！！
        let dataSource = JXSegmentedTitleDataSource()
        dataSource.isTitleColorGradientEnabled = true
        dataSource.titleNormalColor = .gray
        dataSource.titleSelectedColor = UIColor(named: "Color-sysDefaultFontColor")!
        dataSource.titles = titles
        segmentedDataSource = dataSource

        
        //配置指示器
        let indicator = JXSegmentedIndicatorLineView()
        indicator.indicatorWidth = JXSegmentedViewAutomaticDimension
        segmentedView.indicators = [indicator]

        segmentedView.dataSource = segmentedDataSource
        segmentedView.delegate = self

        view.addSubview(self.segmentedView)

        for indicaotr in segmentedView.indicators {
           if (indicaotr as? JXSegmentedIndicatorLineView) != nil ||
               (indicaotr as? JXSegmentedIndicatorDotLineView) != nil ||
               (indicaotr as? JXSegmentedIndicatorDoubleLineView) != nil ||
               (indicaotr as? JXSegmentedIndicatorRainbowLineView) != nil ||
               (indicaotr as? JXSegmentedIndicatorImageView) != nil ||
               (indicaotr as? JXSegmentedIndicatorTriangleView) != nil {
               //navigationItem.rightBarButtonItem = UIBarButtonItem(title: "指示器位置切换", style: UIBarButtonItem.Style.plain, target: self, action: #selector(didIndicatorPositionChanged))
               break
           }
        }
        
        //listContainerView = JXSegmentedListContainerView(dataSource: self)
        view.addSubview(self.listContainerView)
        //关联listContainer
        segmentedView.listContainer = listContainerView
        
        segmentedView.selectItemAt(index: 2)

**Comment by zxmatline** [comment]
问题已经解决。

**Comment by z782223468** [comment]
我的segmentedView 是通过xib设置的  现在设置selectItemAt都没用 请问下你是怎么解决的

**Comment by pujiaxin33** [comment]
> 我的segmentedView 是通过xib设置的 现在设置selectItemAt都没用 请问下你是怎么解决的

@z782223468 初始化之前通过defaultSelectedIndex指定默认的index，显示之后，才使用selectItemAt进行切换

**Comment by z782223468** [comment]
好了好了 感谢
