### ISSUE TITLE
validListDict 取出空值, 崩溃

### ISSUE THREAD

**Issue by lmcmz** [pujiaxin33/JXSegmentedView#55]
iOS 13.0

用.collectionView type, 会有 let list = validListDict[indexPath.item]
list为空情况。

**Comment by pujiaxin33** [comment]
能给出错误的堆栈信息吗？

**Comment by lmcmz** [comment]
一共4个值，进去直接点击 SegementView 从0到3. ListContainer 就崩了。
<img width="782" alt="Screen Shot 2019-10-28 at 5 45 35 pm" src="https://user-images.githubusercontent.com/9669733/67837100-60aeea00-fb42-11e9-859a-7bcaa424050f.png">
<img width="339" alt="Screen Shot 2019-10-30 at 6 21 37 pm" src="https://user-images.githubusercontent.com/9669733/67837133-702e3300-fb42-11e9-8ad7-fd6f11f6ef95.png">

**Comment by pujiaxin33** [comment]
1.0.1版本修复

**Comment by lmcmz** [comment]
神速！点赞
