### ISSUE TITLE
你好 这个contentOffsetY上升的有点猛

### ISSUE THREAD

**Issue by ChristingLi** [pujiaxin33/JXSegmentedView#57]
作者你好，我使用JXPagingView中传入了一个UICollectionView, 向上滑动时，contentOffsetY 会骤然上升

contentOffsetY  -11.333333333333334
contentOffsetY  -6.333333333333333
contentOffsetY  335.0
contentOffsetY  335.0

没能平缓的滑动，而是直接跳到了顶部，我想问下应该从哪里去解决这个问题

**Comment by pujiaxin33** [comment]
请按文档和demo示例代码来，应该是你部分代码没有使用正确
