### ISSUE TITLE
按钮快速点击无响应，有延迟

### ISSUE THREAD

**Issue by PJStation** [pujiaxin33/JXSegmentedView#58]
在`ListBaseViewController`里添加一个按钮
```
let homeButton = UIButton.init(type: .custom)
homeButton.frame = CGRect.init(x: 100, y: 100, width: 46, height: 46)
homeButton.setImage(UIImage.init(named: "ok"), for: .normal)
homeButton.setImage(UIImage.init(named: "ok-1"), for: .highlighted)
view.addSubview(homeButton)
```
normal、highlighted图片需自己添加，
请用模拟器测试后更明显，点击鼠标，快速松指，无反应，鼠标左键按住不动才会高亮

已解决
```
        listContainerView.scrollView.delaysContentTouches = false
```

**Comment by PJStation** [comment]
请问是否试过有这个问题，还是我使用的方法不对

**Comment by pujiaxin33** [comment]
你给发一个复现问题的demo和操作步骤吗？

**Comment by PJStation** [comment]
https://github.com/PJStation/JXSegmentedView

**Comment by Resoulte** [comment]
做的个人主页，快速上拉列表两三秒内点击事件不能触发，两三秒后就可以了，我用你的Demo也是同样结果

**Comment by Resoulte** [comment]
@pujiaxin33

**Comment by pujiaxin33** [comment]
点击哪里？

**Comment by PJStation** [comment]
> 你给发一个复现问题的demo和操作步骤吗？

下载这个https://github.com/PJStation/JXSegmentedView
直接在模拟器上运行，随便一个样式的点击进去，有一个按钮，快速点击按钮没有高亮效果，长按才会有高亮效果
<img width="680" alt="WeChatf2adb80896b98fb312e28d592a338525" src="https://user-images.githubusercontent.com/13344038/69927803-59d61700-14f4-11ea-874b-e556eca0dff2.png">

**Comment by pujiaxin33** [comment]
麻烦你重新发一下截图

**Comment by PJStation** [comment]
> 麻烦你重新发一下截图

截图就是运行后按钮的位置，不是动态图，看不出来什么，你运行一下就看到了

**Comment by pujiaxin33** [comment]
重新发一下按钮所在位置截图就行

**Comment by PJStation** [comment]
> 重新发一下按钮所在位置截图就行

<img width="680" alt="WeChatf2adb80896b98fb312e28d592a338525" src="https://user-images.githubusercontent.com/13344038/69928435-99056780-14f6-11ea-87da-0ace25aeede3.png">

**Comment by pujiaxin33** [comment]
列表上的任意UIControl，即便是UITableViewCell，在滚动的时候，都不会响应点击。因为处于滚动中，事件已经被滚动手势吃掉了。

**Comment by Resoulte** [comment]
@pujiaxin33 是快速上拉到底部然后已经停止滚动后，两三秒内点击事件不能触发

**Comment by pujiaxin33** [comment]
@PJStation 你可以自己按照如下代码，添加点击事件的处理方法，快速点击可以正确响应。至于你关心的图片问题，请自行百度：
```Swift
    override func viewDidLoad() {
        super.viewDidLoad()
        let homeButton = UIButton.init(type: .custom)
        homeButton.frame = CGRect.init(x: 100, y: 100, width: 46, height: 46)
        homeButton.setImage(UIImage.init(named: "ok"), for: .normal)
        homeButton.setImage(UIImage.init(named: "ok-1"), for: .highlighted)
        homeButton.backgroundColor = .red
        view.addSubview(homeButton)
        view.backgroundColor = UIColor(red: CGFloat(arc4random()%255)/255, green: CGFloat(arc4random()%255)/255, blue: CGFloat(arc4random()%255)/255, alpha: 1)
        homeButton.addTarget(self, action: #selector(didClikced), for: .touchUpInside)
    }

    @objc func didClikced() {
        print("didClicked")
    }
```

**Comment by pujiaxin33** [comment]
@Resoulte 麻烦你自己提一个新的Issue，并提供相关信息，不同的问题，不要在一起讨论

**Comment by PJStation** [comment]
原因是UIScrollView 和 UIButton 的事件存在冲突导致的，设置UIScrollView的属性：
`listContainerView.scrollView.delaysContentTouches = false`
