### ISSUE TITLE
Indicator宽度

### ISSUE THREAD

**Issue by WS-Vincent** [pujiaxin33/JXSegmentedView#6]
请问能增加一个枚举吗，比如我想让Indicator的宽度是cellitem的宽度左右各有2个点的距离这种。本来想继承重写getIndicatorWidth方法让宽度减一点点，然后发现在module外写不了~~

**Comment by pujiaxin33** [comment]
已经添加了indicatorWidthIncrement属性，在0.0.7版本发布
