### ISSUE TITLE
上拉到底部然后已经停止滚动后，两三秒内点击事件不能触发

### ISSUE THREAD

**Issue by Resoulte** [pujiaxin33/JXSegmentedView#62]
[1575280896605857.mp4.zip](https://github.com/pujiaxin33/JXSegmentedView/files/3910648/1575280896605857.mp4.zip)

**Comment by pujiaxin33** [comment]
[JXPagingView地址](https://github.com/pujiaxin33/JXPagingView)

关于下方列表视图的代理方法- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath有时候需要点击两次才回调
出现步骤：当手指放在下方列表视图往下拉，直到TableHeaderView完全显示。

原因：经过上面的步骤之后，手指已经离开屏幕且列表视图已经完全静止，UIScrollView的isDragging属性却依然是true。就导致了后续的第一次点击，让系统认为当前UIScrollView依然在滚动，该点击就让UIScrollView停止下来，没有继续转发给UITableView，就没有转化成didSelectRow事件。

解决方案：经过N种尝试之后，还是没有回避掉系统的isDragging异常为true的bug。大家可以在自定义cell最下方放置一个与cell同大小的button，把button的touchUpInside事件当做didSelectRow的回调。因为UIButton在响应链中的优先级要高于UIGestureRecognizer。

代码：请参考TestTableViewCell类的配置。

**Comment by pujiaxin33** [comment]
或者你可以尝试用JXPagingView里面的JXPagerSmoothView

**Comment by Resoulte** [comment]
加UIButton的效果并不明显，看你的demo也是

**Comment by Resoulte** [comment]
决定下个版本用JXPagerSmoothView了，谢谢你
