### ISSUE TITLE
checkIndexValid 发生崩溃  iOS13.3

### ISSUE THREAD

**Issue by czjwarrior** [pujiaxin33/JXSegmentedView#66]
![FD111C0E4A3A74045C90DDB57AA5543E](https://user-images.githubusercontent.com/10876312/71813130-ddff5980-30b3-11ea-82a6-bd48a0a7f023.jpg)
![8E16ABC86EA25F4925C5F84D4C5FD3C5](https://user-images.githubusercontent.com/10876312/71813144-e788c180-30b3-11ea-9d08-a9b6481be6a3.jpg)

**Comment by pujiaxin33** [comment]
错误日志是什么？

**Comment by pujiaxin33** [comment]
dataSource为nil？

**Comment by pujiaxin33** [comment]
1.0.4版本修复
