### ISSUE TITLE
Redundant conformance of 'JXPagingMainTableView' to protocol 'UIGestureRecognizerDelegate'

### ISSUE THREAD

**Issue by bluesky0109** [pujiaxin33/JXSegmentedView#67]
把文件拖入项目 编译不过，报错如下
Redundant conformance of 'JXPagingMainTableView' to protocol 'UIGestureRecognizerDelegate'

Redundant conformance of 'JXPagingListContainerCollectionView' to protocol 'UIGestureRecognizerDelegate'

**Comment by pujiaxin33** [comment]
建议通过cocoapods集成
