### ISSUE TITLE
我集成特殊效果里的自定义列表，第一个列表的naviController是空的是啥问题？

### ISSUE THREAD

**Issue by RockyQu** [pujiaxin33/JXSegmentedView#7]
这导致第一列表点击不能跳转，我是初学，是我少写了某些东西吗？

**Comment by pujiaxin33** [comment]
需要你在创建列表的时候，为列表赋值naviController属性

**Comment by RockyQu** [comment]
再次麻烦你，我对比了代码我写了 
extension SurroundingsViewController: JXSegmentedListContainerViewDataSource {
    func numberOfLists(in listContainerView: JXSegmentedListContainerView) -> Int {
        return segmentedDataSource.dataSource.count
    }
    
    func listContainerView(_ listContainerView: JXSegmentedListContainerView, initListAt index: Int) -> JXSegmentedListContainerViewListDelegate {
        let vc = SurroundingsTableViewController()
        
        Logg(item: index)
        if navigationController == nil {
            Logg(item: "aaaaa")
        }else{
            Logg(item: "bbbbb")
        }
        
        vc.naviController = navigationController
        vc.typeString = segmentedDataSource.titles[index]
        return vc
    }
}

在默认加载第一个列表时这里的 listContainerView 方法的 navigationController 是空的，其他列表（非第一页的列表）都是可以跳转的（navigationController 不是空），这是什么问题？

**Comment by pujiaxin33** [comment]
你可以在第一次的时候打断点自己分析一下。
还有就是使用方法尽量参考示例demo。

**Comment by RockyQu** [comment]
谢谢，我再试试
