### ISSUE TITLE
 JXSegmentedIndicator 有时候出现位置不对

### ISSUE THREAD

**Issue by lmcmz** [pujiaxin33/JXSegmentedView#70]
遇到个奇葩的问题，Indicator 时而出现位置不对的情况。

页面比较复杂，有3个 JXSegmentedView。

完全没啥头绪，第一次打开页面基本没事。
第二次以后基本上，Indicator 位置都是错位的。

截图如下：
| ❌位置不对 |  ✅ 正确 |
|---| ---|
|<img width="584" alt="Screen Shot 2020-02-09 at 2 39 03 pm" src="https://user-images.githubusercontent.com/9669733/74095820-18906200-4b4a-11ea-90f9-b5c3278ef055.png">|<img width="584" alt="Screen Shot 2020-02-09 at 2 38 50 pm" src="https://user-images.githubusercontent.com/9669733/74095824-20500680-4b4a-11ea-892d-44a6e5eb6fda.png">|

👇下面是 3个 indicator 的 init 代码：
```swift
        let indicator = JXSegmentedIndicatorBackgroundView()
        indicator.isIndicatorConvertToItemFrameEnabled = true
        indicator.indicatorHeight = 30
        indicator.indicatorColor = AliceColor.darkGrey()
        segmentedView.indicators = [indicator]
```

**Comment by pujiaxin33** [comment]
看代码没有问题，要是能提供一个复现问题的demo，就好查找具体原因了。

**Comment by lmcmz** [comment]
> 看代码没有问题，要是能提供一个复现问题的demo，就好查找具体原因了。

这个bug很奇怪，有时候出现，有时候不出现。
我看是一个page使用了3个 JXSegmentedView，有使用JXPagingView。

update frame 时候弄混了，拿的是另一个 indicator 的 frame。

**Comment by dawnnnnn** [comment]
> 看代码没有问题，要是能提供一个复现问题的demo，就好查找具体原因了。

在demo里，混合使用的datasource处，添加如下样式
```
dataSource.titleSelectedZoomScale = 1.3
dataSource.titleSelectedStrokeWidth = -2.5
dataSource.isTitleZoomEnabled = true
dataSource.isTitleStrokeWidthEnabled = true
dataSource.isTitleColorGradientEnabled = true
dataSource.isItemSpacingAverageEnabled = false
dataSource.isSelectedAnimable = true
dataSource.isItemWidthZoomEnabled = true
```
从第一项，直接selcted(item: 最后一项)，指示器会出现偏差

**Comment by dawnnnnn** [comment]
以上偏差 多次尝试之后，发现是`isItemWidthZoomEnabled` 导致的

**Comment by pujiaxin33** [comment]
@dawnnnnn 最新的仓库代码已经修复
