### ISSUE TITLE
子模块带下拉刷新有故障

### ISSUE THREAD

**Issue by wangjunling888** [pujiaxin33/JXSegmentedView#72]
首先说一下模块搭建:  类似微博页面,  但是实现的是每个页面单独刷新;

问题复现步骤, 
假设4个页面  abcd 
a页面下拉刷新, 正在刷新的过程中 点击 标签栏b标签,切换到b页面 再下来b,  这时候再回到按页面, 大概率出现a页面不能下拉刷新,  并且a页面也不能上拉, 只能带着外层的scrollview整体上拉,  希望关注下,

 
猜测原因, a页面下拉刷新的过程中,  a页面的tableview处在一个偏移状态,  如果切换到b页面并且下拉, 这个时候ab页面的刷新状态都会控制外层的滑动状态,  所以有一定概率出现a页面或者b页面不能滑动了,

**Comment by pujiaxin33** [comment]
你把JXSegmentedListContainerView的type设置为scrollView，试试呢？

**Comment by pujiaxin33** [comment]
你有使用JXPagingView吗？

**Comment by wangjunling888** [comment]
对用的就是jxpagingview





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 暴走的鑫鑫 <notifications@github.com&gt;
发送时间: 2020年3月11日 10:13
收件人: pujiaxin33/JXSegmentedView <JXSegmentedView@noreply.github.com&gt;
抄送: 崇山峻岭 <987424476@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[pujiaxin33/JXSegmentedView] 子模块带下拉刷新有故障 (#72)




你有使用JXPagingView吗？

**Comment by pujiaxin33** [comment]
@wangjunling888 你使用最新版本的JXPaingView，通过- (instancetype)initWithDelegate:(id<JXPagerViewDelegate>)delegate listContainerType:(JXPagerListContainerType)type方法进行初始化，type选择JXPagerListContainerType_ScrollView。应该就能解决你的问题了。

**Comment by wangjunling888** [comment]
好的，谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 暴走的鑫鑫 <notifications@github.com&gt;
发送时间: 2020年4月9日 09:46
收件人: pujiaxin33/JXSegmentedView <JXSegmentedView@noreply.github.com&gt;
抄送: 崇山峻岭 <987424476@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[pujiaxin33/JXSegmentedView] 子模块带下拉刷新有故障 (#72)
