### ISSUE TITLE
JXSegmentedView.contentScrollView 宽度为0导致奔溃

### ISSUE THREAD

**Issue by 224duan** [pujiaxin33/JXSegmentedView#76]
奔溃发生在 `JXSegmentedView.swift` 114 行
```var progress = contentOffset.x/contentScrollView!.bounds.size.width```
当`JXPagingView` 有超过屏幕高度的 header 时，通过测滑退出控制器时发生奔溃。
测试发现是因为 `contentScrollView!.bounds.size.width == 0`导致的

**Comment by pujiaxin33** [comment]
最新的仓库版本已经修复，后续会出新包
