### ISSUE TITLE
isSelectedAnimable设置为true的情况下，选中最后一个item，indicator位置没有居中

### ISSUE THREAD

**Issue by iamjjh** [pujiaxin33/JXSegmentedView#77]
//配置数据源
            let dataSource = JXSegmentedTitleImageDataSource()
            dataSource.isTitleColorGradientEnabled = true
            dataSource.titles = titles
            dataSource.titleImageType = .rightImage
            dataSource.isImageZoomEnabled = true
            dataSource.isTitleZoomEnabled = true
            dataSource.titleSelectedZoomScale = 1.5
            dataSource.titleSelectedStrokeWidth = -2
            dataSource.isTitleStrokeWidthEnabled = true
            dataSource.isItemWidthZoomEnabled = true
            dataSource.isSelectedAnimable = true
            dataSource.normalImageInfos = ["monkey", "frog", "dog", "pig", "sheep", "chicken", "horse", "cow", "elephant", "dragon"]
            dataSource.loadImageClosure = {(imageView, normalImageInfo) in
                //如果normalImageInfo传递的是图片的地址，你需要借助SDWebImage等第三方库进行图片加载。
                //加载bundle内的图片，就用下面的方式，内部默认也采用该方法。
                imageView.image = UIImage(named: normalImageInfo)
            }
            //配置指示器
            let indicator = JXSegmentedIndicatorLineView()
            indicator.indicatorWidth = 10
            vc.segmentedView.indicators = [indicator]
            vc.segmentedDataSource = dataSource

**Comment by pujiaxin33** [comment]
最新仓库代码已修复，后续会发新包
