### ISSUE TITLE
deviceOrientationDidChanged崩溃问题~

### ISSUE THREAD

**Issue by WS-Vincent** [pujiaxin33/JXSegmentedView#8]
<img width="683" alt="屏幕快照 2019-03-15 上午10 36 34" src="https://user-images.githubusercontent.com/15700421/54404623-20b00980-470f-11e9-9c3f-9332fb1a6a61.png">
<img width="615" alt="屏幕快照 2019-03-15 上午10 36 24" src="https://user-images.githubusercontent.com/15700421/54404624-20b00980-470f-11e9-9877-bbaf1dbbc8bd.png">
<img width="390" alt="屏幕快照 2019-03-15 上午10 36 16" src="https://user-images.githubusercontent.com/15700421/54404625-2148a000-470f-11e9-9e3c-7a51df4e3b85.png">
偶尔会崩溃，没太注意，项目比较忙，大佬有时间看看是BUG还是模拟器才有的~

**Comment by pujiaxin33** [comment]
我已经更新了示例项目的JXPagingView，你有空可以试一下最近版本。我自测了没有问题
