### ISSUE TITLE
bug：mj_header.beginRefreshing()无下拉动画

### ISSUE THREAD

**Issue by JayLin0920** [pujiaxin33/JXSegmentedView#82]
**demo**
楼主现有的demo，下载下来，修改下就可以复现，复现步骤在如下

**问题描述**
通过点击segment上的标签，触发mj_header.beginRefreshing()
- 有问题处：当segment处于第一个标签时，无下拉动画
- 无问题处：segment处于非第一个标签，有下拉动画

（该问题仅在，segment并不处置顶也不是处于最下，也就是让此时的segment既可以向上滑也可以向下滑，这种情况下，才无下拉动画） 

**复现步骤**
1、楼主的demo中加入如下代码
```
1、BaseViewController中，添加通知
func segmentedView(_ segmentedView: JXSegmentedView, didClickSelectedItemAt index: Int) {
        print("jl==   didClickSelectedItemAt")
        NotificationCenter.default.post(name: NSNotification.Name(rawValue: "NotificationCenter_didClickSelectedItemAt"), object: nil)
    }

2、ListViewController中，监听通知
NotificationCenter.default.addObserver(self, selector: #selector(ntf), name: NSNotification.Name(rawValue: "NotificationCenter_didClickSelectedItemAt"), object: nil)
@objc func ntf() {
        if isNeedHeader {
            print("jl== beginRefreshing")
            self.tableView.mj_header.beginRefreshing()
        }
    }
```
2、demo点击步骤
（1）启动app，点击进入‘列表下拉刷新’页面
（2）进入页面后，让页面稍微往上面滑动一点（让segment并不处置顶也不是处于最下，也就是让此时的segment既可以向上滑也可以向下滑）
（3）点击segment上的’能力‘，会触发 ’mj_header.beginRefreshing()‘，此时没有mj的自动下拉的动画效果（如果点击的是第二个标签’爱好‘，是有自动下拉的动画效果）

**期望**
能修复下这个问题

**Comment by pujiaxin33** [comment]
swift demo里面没有BaseViewController和ListViewController类

**Comment by JayLin0920** [comment]
😯，我提问题提错了，是这个库，JXPagingView

**Comment by JayLin0920** [comment]
不好意思，这个是JXPagingView库的，我已经把问题发到那个库上了，这个我关了哦
