### ISSUE TITLE
获取点击的listview

### ISSUE THREAD

**Issue by zgicg** [pujiaxin33/JXSegmentedView#86]
![image](https://user-images.githubusercontent.com/8198108/82205197-c759f080-9938-11ea-83ad-6f5a91e6ad0b.png)
![image](https://user-images.githubusercontent.com/8198108/82205294-ef495400-9938-11ea-82af-b16ea3c9f9f0.png)
没有cellForRow方法吗？兄嘚

**Comment by pujiaxin33** [comment]
获取列表通过`JXSegmentedListContainerView`的`validListDict`属性获取
