### ISSUE TITLE
是否考虑添加Rx支持？

### ISSUE THREAD

**Issue by xueyongwei** [pujiaxin33/JXSegmentedView#87]
确实好用，哈哈哈！

**Comment by pujiaxin33** [comment]
需要针对RX添加哪些支持呢？

**Comment by xueyongwei** [comment]
JXSegmentedListContainerView创建的时候需要指定dataSource，貌似无法支持Rx了。

**Comment by xueyongwei** [comment]
如果只是使用JXSegmentedView，对Delegate常用的didSelectedIndex很容易实现Rx支持，但是JXSegmentedListContainerView的dataSource我暂时还没有找到好的方法。

**Comment by pujiaxin33** [comment]
这个你自己支持吧，这个库对rx的需求不高。
