### ISSUE TITLE
SegmentedView 对齐

### ISSUE THREAD

**Issue by anddygon** [pujiaxin33/JXSegmentedView#88]
首先感谢作者打造这么灵活的库!

我在使用的时候遇到下面小问题，请问目前有办法解码？简单查看了源码 没发现相关设置，issue也没有人提过。我的问题如下

如图，titles足够的话显示正常，
![image](https://user-images.githubusercontent.com/7263780/82789476-eb6b8380-9e9c-11ea-9ce4-46a8658521ad.png)

但是如果title只有2，3个的时候，会自动放大title之间间距，希望title不足的情况下 能设置对齐，留出空白，而不是像下面这样填充
![image](https://user-images.githubusercontent.com/7263780/82790535-c8da6a00-9e9e-11ea-87a1-7c685ec37bb3.png)

**Comment by YangChaoJie** [comment]
缩小中间间距的话，可以用segmentedView.contentEdgeInsetLeft或者segmentedView.contentEdgeInsetRight 缩小两端的距离

**Comment by anddygon** [comment]
ReadMe里面有示例， isItemSpacingAverageEnabled款已解决

**Comment by ishall1** [comment]
楼主处理过居中对齐吗？

**Comment by anddygon** [comment]
不足时居中 我是通过自定义segment layout解决的
