### ISSUE TITLE
需求：顶部最左边有个“全部”，且不会跟随顶部标题滑动的

### ISSUE THREAD

**Issue by zhangjianjun056** [pujiaxin33/JXSegmentedView#89]
需求：
顶部最左边有个“全部”，且不会跟随顶部标题滑动的，如下：
全部     周一    周二   周三   周四    周五   周六   周日

其中：”全部”不会跟随”周一~周日”滑动，手动滑动下面的列表view后，选中对应的“全部”。
手动点击“全部”时，下面的列表view会自动的滑动到对应的view

**Comment by pujiaxin33** [comment]
只能自己去修改listContainerView进行支持了。目前listContainerView和titles的数量是需要相同的。你的需求要求全部固定在最左边，那么全部就只能作为单独的按钮实现。所以，最终就是上面的JXSegmentedView的数据源是【周一 周二 周三 周四 周五 周六 周日】，但是下面的listContainer却要有8个列表。

**Comment by zhangjianjun056** [comment]
嗯嗯，是的，谢谢你------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;暴走的鑫鑫&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月1日(星期一) 上午10:26
收件人:&nbsp;&quot;pujiaxin33/JXSegmentedView&quot;<JXSegmentedView@noreply.github.com&gt;;
抄送:&nbsp;&quot;闲云悠鹤蝶恋舞&quot;<184205206@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pujiaxin33/JXSegmentedView] 需求：顶部最左边有个“全部”，且不会跟随顶部标题滑动的 (#89)
