### ISSUE TITLE
如果顶部 segmentedView的 collectionView 实时滑动时, contentScrollView 也需要跟着实时滑动

### ISSUE THREAD

**Issue by burning-git** [pujiaxin33/JXSegmentedView#90]
请问下，如果顶部 segmentedView的 collectionView 实时滑动时, contentScrollView 也需要跟着实时滑动，这个需要 怎么改动 最小呢

**Comment by pujiaxin33** [comment]
我不知道你的具体需求，只是一个简单的描述无法确定如何解决。有现有的app效果吗？

**Comment by burning-git** [comment]
顶部的contentoffset 滑动了，下面的 scoller 也需要同步滚动

**Comment by burning-git** [comment]
顶部的scollerview 滑动了，下面的 scollerview 也需要同步滚动, 目前 是顶部的scollerview 滚动了，下面的scollerview不会 滚动，只有顶部点击了，下面的scollerview 才会滚动

**Comment by pujiaxin33** [comment]
我知道你的意思，但是要有具体的效果，才能确定细节。

**Comment by burning-git** [comment]
参考app：
选择相册的时候
https://apps.apple.com/us/app/slideshow-add-music-to-photos/id919610704

**Comment by pujiaxin33** [comment]
截图，你自己能打开这个链接吗？

**Comment by burning-git** [comment]
忘了，是美区的账号,appname: slideshow 
我录制一个视频 ,顶部滑动时 (操作视频不好看出来是顶部滑动)
视频连接
http://burning.9191pow.com/RPReplay_Final1590722329.MP4

**Comment by pujiaxin33** [comment]
这个支持不了，得自己大改了。

**Comment by burning-git** [comment]
嗯，我看了下 源码，如果想做成这样的效果，代码得大改动，所以问问 大佬的意见，然后再 决定

**Comment by pujiaxin33** [comment]
你可以完全自己从零开始写，就怕源码有许多地方不方便支持，改起来就会很累，看你自己了。
