### ISSUE TITLE
侧滑返回手势 与 listContainerView.scrollView 的手势冲突 

### ISSUE THREAD

**Issue by Marcello168** [pujiaxin33/JXSegmentedView#94]
侧滑返回手势 与 listContainerView.scrollView 的手势冲突  如果把列表容器禁止左右滑动 是可以侧滑返回的 这有办法解决吗，谢谢

**Comment by pujiaxin33** [comment]
你看一下示例代码的处理方式呢

**Comment by Marcello168** [comment]
> 你看一下示例代码的处理方式呢

看了下 JXCategoryView 的全屏手势处理 解决了 谢谢
