### ISSUE TITLE
1.1.0版本崩溃

### ISSUE THREAD

**Issue by ganweiming** [pujiaxin33/JXSegmentedView#95]
![企业微信截图_0ec86e86-49b6-4e20-a797-2a3bdf1902e8](https://user-images.githubusercontent.com/18005096/84220832-602df700-ab06-11ea-8fd9-0d8b6d064389.png)
更新至1.1.0版本后崩溃,JXSegmentedTitleDataSource错误

**Comment by pujiaxin33** [comment]
你clear一下项目再试一试呢

**Comment by ganweiming** [comment]
@pujiaxin33 有用,十分感谢
