### ISSUE TITLE
冷启动快速滑动后往回滑动，可能导致JXSegmentedListContainerView的index不准确

### ISSUE THREAD

**Issue by iamjjh** [pujiaxin33/JXSegmentedView#96]
冷启动快速滑动后往回滑动，马上点击控制器中内容Push到新页面，可能导致`JXSegmentedListContainerView`的`index`不准确。

打印日志发现`JXSegmentedViewDelegate`中`func segmentedView(_ segmentedView: JXSegmentedView, didSelectedItemAt index: Int)`打印的`index`与`JXSegmentedListContainerView`在`private func listDidAppear(at index: Int)` 中为`currentIndex`赋值的`index`不一致。

**Comment by pujiaxin33** [comment]
麻烦你用最新版本1.2.7测试一下呢？如果还能复现，麻烦详情描述一下你通过demo复现的步骤。
