### ISSUE TITLE
两层筛选结构会出现多次调用listDidAppear事件

### ISSUE THREAD

**Issue by ldy694** [pujiaxin33/JXSegmentedView#98]
![image](https://user-images.githubusercontent.com/10148802/85195501-9d179c00-b305-11ea-830a-f99efabc473c.png)
如果所示结构,切换tabbar，到其它页面，再切回到当前页面，这时listDidAppear会调用两次

**Comment by ldy694** [comment]
viewDidAppear也会调用两次，我用的是UIViewController做为子视图

**Comment by ldy694** [comment]
我找到真正执行两次的原因了，是因为我调用了更新角标的操作，让列表刷新了
![image](https://user-images.githubusercontent.com/10148802/85196113-790a8980-b30a-11ea-9a24-2704c531927b.png)


请教一下，有没有方法只更新小圆点，不更新列表吗？

**Comment by pujiaxin33** [comment]
`func reloadItem(at index: Int)`
